### ISSUE TITLE
Use of DataProcessor's in combination with Flux Templates possible?

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#1842] opened 2020-10-12 10:40 UTC
I really would love to use MenuProcessor with Flux Pages. Is this possible somehow?

```
    dataProcessing {
        10 = TYPO3\CMS\Frontend\DataProcessing\MenuProcessor
        10 {
            special = list
            special.value.field = pages
            levels = 7
            as = menu
            expandAll = 1
            includeSpacer = 1
            titleField = nav_title // title

            dataProcessing {
                10 = TYPO3\CMS\Frontend\DataProcessing\FilesProcessor
                10 {
                    references.fieldName = media
                }
            }
        }
    }
```

**Comment by NamelessCoder** [comment] 2020-10-12 11:39
Duplicate of https://github.com/FluidTYPO3/flux/issues/1843 (which I transferred to Flux repo just now); an alternative solution is also recorded there. Please follow status there. A solution is already proposed but it looks like @svewap hasn't had time to create a PR. If you wish to take over that would be appreciated!

**Closed by NamelessCoder** 2020-10-12 11:39 UTC

**Comment by typoworx-de** [comment] 2020-12-21 14:05
@NamelessCoder i've done it myself in the meantime:

```
<?php
namespace TYPOworx\TnmPackageMbdx\Controller;

use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface;
use TYPO3\CMS\Frontend\ContentObject\ContentDataProcessor;
use FluidTYPO3\Flux\Controller\PageController as FluxPageController;

/**
 * Class PageController
 * @package TYPOworx\TnmPackageFooBar\Controller
 * @route off
 */
class PageController extends FluxPageController
{
    protected function initializeViewVariables()
    {
        parent::initializeViewVariables();

        $cObj = $this->configurationManager->getContentObject();
        $dataProcessor = GeneralUtility::makeInstance(ContentDataProcessor::class);

        $tsExtensionKey = sprintf('tx_%s.', str_replace('_', '', $this->request->getControllerExtensionKey()));

        $typoscriptConfig = $this->configurationManager->getConfiguration(ConfigurationManagerInterface::CONFIGURATION_TYPE_FULL_TYPOSCRIPT);
        $typoscriptConfig = isset($typoscriptConfig['plugin.'][ $tsExtensionKey ])
            ? $typoscriptConfig['plugin.'][ $tsExtensionKey ]
            : null
        ;

        $variables = [];
        if(isset($typoscriptConfig['dataProcessing.']) && count($typoscriptConfig['dataProcessing.']))
        {
            $variables = $dataProcessor->process($cObj, $typoscriptConfig, $variables);
        }

        $this->view->assignMultiple($variables);
    }
}
```

and ext_localconf.php
```
        $GLOBALS['TYPO3_CONF_VARS']['SYS']['Objects'][ \FluidTYPO3\Flux\Controller\PageController::class ] = [
            'className' => \TYPOworx\TnmPackageFooBar\Controller\PageController::class
        ];
```

As you can see there's not much magic on this and I really would like to have this implemented in Flux native PageController as well :+1:

**Comment by cweiske** [comment] 2024-12-03 14:35
Referenced issue https://github.com/FluidTYPO3/flux/issues/1843  has been deleted.

@typoworx-de code still works with flux 10 when adjusting the `initializeViewVariables` method signature and using the passed `$view` object.
