### ISSUE TITLE
Can't access Flux fields in Content Element unless BE user is admin

### ISSUE THREAD

**Issue by Chris-dev** [FluidTYPO3/flux#1494] opened 2017-12-14 11:25 UTC
TYPO3 8.7.9
Flux development
fluidpages development
vhs development

Provider extension created with _builder_, then removed fluidcontent from requirements. 

Backend users (editors) who aren't admin can't access any flux fields in a FCE content element created with flux. They can add the FCE and see all other allowed standard typo3 fields, but the whole "Plugin Options" part is missing.

For testing, I tried it in a new installation with just the "Example element" from the _builder_ and gave the backend user group access to all fields, but I still can't access the Flux fields.

**Comment by Ismaelbidau** [comment] 2018-01-11 09:56
Does anybody have any clue ? I switch TYPO3 in version 8.7.9 without seen this problem. My users can't modify Flexform field anymore !
(try with flux and flux-development)

**Comment by xf-** [comment] 2018-01-13 12:04
Duplicate of #1477

**Closed by xf-** 2018-01-13 12:04 UTC

**Comment by FailXSiegen** [comment] 2018-01-21 16:08
Exactly same issues here. Any fixes avaiable yet?
