### ISSUE TITLE
Copy function of TYPO3 10.4 broken

### ISSUE THREAD

**Issue by cehret** [FluidTYPO3/flux#1840] opened 2020-10-06 22:37 UTC
I have several TYPO3 10.4.9 Installations with flux 9.4.2 installed and it seems that flux breaks the copy function of the backend. 
In most cases when I try to copy a single Element and want to paste it, I get the message that I MOVE the element not COPY.
If I try to copy in List - Mode it ask if I want to copy but if I confirm I get an exception:

![image](https://user-images.githubusercontent.com/5031075/95267276-26ab9500-0835-11eb-9c6f-f40b44f2e71c.png)

Can anyone confirm this? I can reproduce it on two 10.4.9 and one 10.4.8 Installation.

Thank you

Christian

**Comment by toco3** [comment] 2020-10-06 22:56
I download the version of flux here from GitHub and with this version it seems that the issue is solved?

**Comment by NamelessCoder** [comment] 2020-10-07 07:59
Hi Christian - there should be no difference in the copy/move logic of 9.4.2 compared to current GitHub development branch so I'm not sure why that behaves differently for you. IIRC, there was a fix for this between 9.4.1 and 9.4.2 - are you sure you didn't have 9.4.1 on the sites that exhibited the problem?

**Comment by toco3** [comment] 2020-10-07 08:17
Hi, 
thank you for your fast response. Yes you were right - I don't know why it was not proposed for Update in Extension Manager on the TYPO3 Installation - I saved a backup of the flux extension and it ist: 9.4.1 :-O
But there is another issue with I recognized using 9.4.1:
The confirmation dialog is always this one:
![image](https://user-images.githubusercontent.com/5031075/95305053-c3961e80-0885-11eb-9e6b-eed25ce552a2.png)
There is no difference between copy and paste anymore. 

And the german one is not completely translated:
![image](https://user-images.githubusercontent.com/5031075/95305206-f3452680-0885-11eb-880f-52a8c92f653a.png)

(I used the install tool to update the german language pack - no difference :-( )

On the other installation I cannot update 9.4.1 to 9.4.2 because than the backend is broken :-O
![image](https://user-images.githubusercontent.com/5031075/95305392-31dae100-0886-11eb-9beb-f11988949963.png)

I updated all other extensions and I'm not sure why there is a problem - I think I have to dig in here a little deeper :-O

Thank you

Christian

**Comment by NamelessCoder** [comment] 2020-10-07 08:39
> The confirmation dialog is always this one:
> There is no difference between copy and paste anymore.
> And the german one is not completely translated:

I'm afraid this isn't caused by Flux, it's likely a core issue.

> On the other installation I cannot update 9.4.1 to 9.4.2 because after the update of the extension the backend is broken :-O

This error indicates you've got one or more Flux-enabled elements (likely content types) which do not contain a `<flux:form>` in the `Configuration` section. You can fix it by adding this tag. There is a pull request opened to fall back to a vanilla form in these cases, on https://github.com/FluidTYPO3/flux/pull/1834.

**Comment by toco3** [comment] 2020-10-07 08:49
Thank you, I'll check this!

**Comment by moe2k** [comment] 2021-03-30 08:24
Issue confirmed with TYPO3 9.5.26.

**Comment by NamelessCoder** [comment] 2021-05-24 10:12
List copy/paste problem solved by https://github.com/FluidTYPO3/flux/commit/571bc43326af7bbec402c0aa95362b811ea2a4f0.

Issue with setOption called on null solved by https://github.com/FluidTYPO3/flux/commit/64fc2daa4034937ffb9616a5fa5e57ec58391e35.

**Closed by NamelessCoder** 2021-05-24 10:12 UTC
