### ISSUE TITLE
Superfluous p-tags in RTE enabled textfields after save 

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/flux#1482] opened 2017-11-22 15:21 UTC
When saving a text in a fluidcontent text field, RTE (ck_editor) always adds an empty p tag.

There is a closed issue in fluidcontent about this.
https://github.com/FluidTYPO3/fluidcontent/issues/407

I still have this issue in
fluidcontent 	5.2.0 
fluidpages 	4.1.0 
flux 	8.2.1 

Therefor i make a new issue.

**Comment by alandolsi** [comment] 2017-12-10 11:47
I have the same Problem, ckeditor with flexform and ckeditor in flux field.

**Comment by grimmcreative** [comment] 2017-12-10 11:52
fluidcontent is deprecated

Use this FLUX Fork. Issue fixed here.
https://github.com/grimmcreative/flux/tree/master

**Comment by NamelessCoder** [comment] 2017-12-25 22:55
Fluidcontent does not affect this - the problem is solved in Flux `dev-development` and will be in the next release. See https://github.com/FluidTYPO3/flux/pull/1438.

**Closed by NamelessCoder** 2017-12-25 22:55 UTC
