### ISSUE TITLE
flux:  overrides Backendlayoutview fieldName is always null

### ISSUE THREAD

**Issue by Alaarafeh** [FluidTYPO3/flux#1623] opened 2018-10-02 15:36 UTC
When I want to add new content in typo3 Backend layout the Column comes from Page Layout-subpages in the page properties. I have checked and i guess that the Function : 
```
`protected function resolvePrimaryProviderForRecord(string $table, array $record)
    {
       return GeneralUtility::makeInstance(ObjectManager::class)
            ->get(FluxService::class)
            ->resolvePrimaryConfigurationProvider($table, null, $record, null, GridProviderInterface::class);
    }`
```
Here when the table "pages" the $fieldName (the second parameter in function "resolvePrimaryConfigurationProvider") must comes with the Value PageProvider::FIELD_NAME_MAIN, and null when the table is tt_content.
when I change the function to :
```
` protected function resolvePrimaryProviderForRecord(string $table, array $record)
    {
        $fieldName = null;
        if($table == "pages")
            $fieldName = PageProvider::FIELD_NAME_MAIN;

        return GeneralUtility::makeInstance(ObjectManager::class)
            ->get(FluxService::class)
            ->resolvePrimaryConfigurationProvider($table, $fieldName, $record, null, GridProviderInterface::class);
    }`
```
it works fine.
can anyone tell me if it is Bug or I miss something here.
Environment:
TYPO3 8.7.19
Flux 9.0.1
fluidpages 4.2.0

**Comment by NamelessCoder** [comment] 2018-10-02 17:05
This may be a misunderstanding - `fluidpages` is itself responsible for returning the right Provider class based on how you configured the two "Page Layout" fields. If the sub page Provider is supposed to be used (that's the one that inherits parent's template selection and template values) then the primary page Provider shouldn't trigger.

Most likely you actually experience both of those Providers being called but only one of them being used as primary, and it would be the one that reads values from the parent page. This means that internally that provider is expected to walk through the page rootline until it finds the necessary template selection, then uses that value as if it were defined in the child record directly (= straight up inherits the value).

If there is a problem I think it would have to be in one of the two page Provider classes from `fluidpages`, with the wrong one being selected _for some reason_ in your specific use case. Either that or the right Provider class is resolved but it then resolves the wrong template file. It would help a lot if you can debug further and determine what we're actually dealing with here... because forcing Flux to do something to change how Fluidpages works, is not the solution we need ;)

**Comment by ilomedia** [comment] 2018-10-10 09:27
Hi,

i experience the exact same problem and opened an issue here : https://github.com/FluidTYPO3/fluidpages/issues/388

**Comment by NamelessCoder** [comment] 2018-10-10 10:15
You may find https://github.com/FluidTYPO3/fluidpages/issues/388 and https://github.com/FluidTYPO3/fluidpages/issues/391 relevant to your issue. Indeed, #388 looks like a duplicate of this exact report.

**Comment by NamelessCoder** [comment] 2019-04-22 16:08
Solved via https://github.com/FluidTYPO3/fluidpages/issues/388

**Closed by NamelessCoder** 2019-04-22 16:08 UTC
