### ISSUE TITLE
ConfigurationManager data empty v12

### ISSUE THREAD

**Issue by steffen-hph** [FluidTYPO3/flux#2130] opened 2023-09-04 07:26 UTC
When using the ConfigurationManager the "data" array is empty, while flux is active.
We tried your approach to switch to the ConfigurationManagerInterface instead and it worked, but this is not an option for extensions like Powermail or News.

Powermail (eap for v12) also uses this, which is why it is currently not possible to send the form.

Sounds like https://github.com/FluidTYPO3/flux/issues/2129 and https://github.com/FluidTYPO3/flux/issues/2126

Not working:
```
use TYPO3\CMS\Extbase\Configuration\ConfigurationManager;
$configurationManager = GeneralUtility::makeInstance(ConfigurationManager::class);

\TYPO3\CMS\Core\Utility\DebugUtility::debug($configurationManager->getContentObject()->data);
```
Result: Empty

Working:
```
use TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface;
$configurationManager = GeneralUtility::makeInstance(ConfigurationManagerInterface::class);

\TYPO3\CMS\Core\Utility\DebugUtility::debug($configurationManager->getContentObject()->data);
```
Result: The record stuff

TYPO3 12.4.5
Flux: Latest from today (2023-09-04)

**Comment by Konafets** [comment] 2023-09-06 09:07
I have the same issue while sending a Powermail formular. 

> PHP Warning: Undefined array key "pi_flexform" in /Users/user/Sites/example.com/public/typo3conf/ext/powermail/Classes/Domain/Validator/AbstractValidator.php line 147

**Comment by NamelessCoder** [comment] 2023-09-06 12:46
Duplicate of https://github.com/FluidTYPO3/flux/issues/2126, please follow that issue for status.

**Closed by NamelessCoder** 2023-09-06 12:46 UTC

**Comment by sdelcroix** [comment] 2023-09-07 06:56
@steffen-hph Could you test the last development version and confirm that it fixes your issue ?

**Comment by steffen-hph** [comment] 2023-09-07 07:29
@sdelcroix I confirm this fix 👍
