### ISSUE TITLE
flux:form.data returning empty array

### ISSUE THREAD

**Issue by davewardle** [FluidTYPO3/flux#776] opened 2015-03-02 09:54 UTC
Hi,

A change made in the last couple of weeks seems to have stopped the form.data viewhelper from working; it now to return an empty array.

Eg, the following (trimmed + edited) code was working until I checked out the latest development branch on Friday.

    <flux:form.data field="tx_fed_page_flexform" table="pages" uid="{testid}" as="fluxPageData">
        {fluxPageData.test}
    </flux:form.data>

I've looked into the code for the viewhelper and I have managed to bodge a temporary fix on my site my changing line 77:
`$providers = $this->configurationService->resolveConfigurationProviders($table, $field, $record);`
to be
`$providers = array();`
so that `readDataArrayFromProvidersOrUsingDefaultMethod` uses a different method for retrieving the values.

I'm afraid that I don't know the extension well enough to debug any further. I've had a look at the history for FluxService but can't see anything that has changed in that particular function over the last couple of weeks so it may be a bit deeper.

Please let me know if you need any further information or if I can do anything else to help.

Thanks

**Comment by NamelessCoder** [comment] 2015-03-02 13:25
Hi Dave - and welcome to GitHub!

The expected behavior in this code is to resolve either a PageProvider or SubPageProvider instance (since you're using `development` the PageProvider is now split in two) and then consult the Provider to return the flexform values. The idea is that the SubPageProvider will get resolved if the current page inherits the page template - and internally, the SubPageProvider should walk the page root line to merge inherited values from parent pages that use the same template.

If there is an error in there, I suspect it is either when resolving the Provider (you may get PageProvider when you need SubPageProvider) or inside the SubPageProvider when reading flexform values, possibly affected by inheritance.

I'll investigate this when I get the time! Thanks for reporting ;)

**Comment by davewardle** [comment] 2015-03-03 09:36
Thanks Claus. In the meantime, I'll look into the code of the PageProvider and SubPageProvider and try to get a great understanding of it all.

**Comment by NamelessCoder** [comment] 2015-03-14 20:20
Hi Dave - would you mind checking this one again? We've had a few fixes for the main/sub page provider issue since we last spoke and those fixes should have an effect in this case.

**Comment by robtwk** [comment] 2015-03-16 10:16
Hi Claus

I pulled the latest dev branch of flux, fluidpages, and fluidcontent so I could test but instead just received the following error: `Could not analyse class:FluidTYPO3\Flux\ViewHelpers\Flexform\SectionViewHelper maybe not loaded or no autoloader?`. 

Odd one as all namespaces seem to be declared properly. I spent about an hour trying to fix this but without luck so I have reverted back. I'll try again later today.

Dave

**Comment by NamelessCoder** [comment] 2015-03-16 11:51
Hi Dave,

I think the problem might be that you have a `flux:flexform.section` which should be `flux:form.section`. We renamed some of these a while back - based on your info now I'm thinking this would work if you get rid of all old usages of ViewHelpers, because the template is clearly being processed ;)

**Comment by davewardle** [comment] 2015-03-16 12:39
Hi Claus

Yes, you are quite right. I thought I had updated them all to the new name but one managed to slip through! I have updated it now and all seems to be working properly now including the the form.data viewhelper.

Many thanks for your help

Dave

**Comment by NamelessCoder** [comment] 2015-03-16 13:09
That *is* good news :)

Excellent - have a nice day!

**Closed by NamelessCoder** 2015-03-16 13:09 UTC
