### ISSUE TITLE
flux:field.select multiple not working as expected

### ISSUE THREAD

**Issue by MrMooky** [FluidTYPO3/flux#1245] opened 2016-12-14 12:02 UTC
Our selectbox is ignoring the **multiple="TRUE"** option:

`<flux:field.select name="filterauswahl" items="alle,marke,corporate,online,kampange" default="alle" size="6" multiple="true" minItems="1" label="Filterkategorie(n)" />`

The backend select itself looks fine, but the option multiple is not added to the select box:

![screen shot 2016-12-14 at 1 01 39 pm](https://cloud.githubusercontent.com/assets/3603346/21181302/7e9cc658-c1fd-11e6-85cb-f5a22bd773df.png)

We're currently using flux 7.4.0

**Comment by NamelessCoder** [comment] 2016-12-14 12:36
If I recall: `flux:field.select` requires `maxItems="2"` (or any other value higher than 1) or the arguments do not get included in the TCEforms data structure. Please check this before I dig into the code and try to reproduce it ;)

**Comment by MrMooky** [comment] 2016-12-14 12:42
The attached screenshot and my code example do not reflect the same state. As you can see in the screenshot, a maxItems="3" has been given. But no sign of a multiple selection.

I even edited the select within the console and added a multiple tag so see if my browser is behaving funny, but doing so allowed me to select multiple items. Could not save them though...

So, this seems to be a bug.

**Comment by NamelessCoder** [comment] 2016-12-14 12:50
Could you give this a try with `dev-development`? https://github.com/FluidTYPO3/flux/commit/d292d1e0f4abda3e780e7d83dfd0ebad8eee15a8 affected the inheritance tree of this ViewHelper, and might have affected the respect for the `multiple` or `maxItems` options too.

Odd thing: In Flux, maximum items is named `maxItems`. In TCEforms it is named `maxitems`. So Flux will yield a TCEforms setting named `maxitems` but your example with the JS instructions contains `maxItems`. I'm not sure if this is an inconsistency in the core (JS names changed but TCEforms names the same) or caused by renaming/deprecating the `maxitems` and `minitems` names so `maxItems` etc. are expected.

https://github.com/FluidTYPO3/flux/blob/development/Classes/Form/AbstractMultiValueFormField.php#L104 shows where we transfer these values to TCEforms, and shows that `multiple` should also be passed (I checked that the ViewHelper also passes it).

**Comment by MrMooky** [comment] 2016-12-14 15:29
Using the development branch caused an error which prevented me from logging in to the backend:

> Fatal error: Trait 'TYPO3Fluid\Fluid\Core\ViewHelper\Traits\CompileWithRenderStatic' not found in /html/typo3/typo3conf/ext/flux/Classes/ViewHelpers/AbstractFormViewHelper.php on line 26

**Comment by NamelessCoder** [comment] 2016-12-14 16:02
Requires TYPO3 7.6.13+ or 8.4.1+

**Comment by MrMooky** [comment] 2016-12-14 16:38
Mh. We're currently not able to update TYPO3 to the latest version (using 7.6.11 right now). We will need to check that at a later time. I solved it with multiple checkboxes for now.

This can be closed, but I'm pretty sure we are not the only ones having this issue.

**Comment by NamelessCoder** [comment] 2017-01-19 17:05
Fixed in 8.0.0

**Closed by NamelessCoder** 2017-01-19 17:05 UTC

**Comment by wazum** [comment] 2017-02-06 09:45
This is still open :-(
Flux 8.0.1
See attached screenshot. The values are OK, but the output select does not contain a multiple attribute.
![screen shot 2017-02-06 at 10 44 44](https://cloud.githubusercontent.com/assets/146727/22642025/4faeac5e-ec59-11e6-8960-bc7ec075985b.png)
![screen shot 2017-02-06 at 10 35 42](https://cloud.githubusercontent.com/assets/146727/22642026/4fb218da-ec59-11e6-811d-2696e44b1d19.png)

**Comment by wazum** [comment] 2017-02-08 20:47
The problem is, that render type is set to 'selectSingle' which does not support 'multiple'. I fixed it by adding 
`$this->setRenderType('selectSingleBox');`
if `$this->getMultiple()` is true.
