### ISSUE TITLE
Cannot add flexform section objects when logged as a backend user with access limited to a language.

### ISSUE THREAD

**Issue by Mbigha** [FluidTYPO3/flux#1899] opened 2021-08-19 10:35 UTC
I have FCEs which all work well for any logged in backend user who has access to all languages.
But if a user's access is limited to a language, and that user is logged in, the "**Add**" button which is clicked to add '`flux:form.object`'s to a `flux:form.section` section is missing.
So this user cannot add new objects.

Any solutions for this?

TYPO3 v9.5.29
Flux v9.5.0

Below are screenshots showing one of the FCEs with and without the "**Add**" button.
![fce-with-add-button](https://user-images.githubusercontent.com/8692016/130054237-1370ee6e-cd43-40d8-835f-ef011fef79ae.png)

![fce-without-add-button](https://user-images.githubusercontent.com/8692016/130054240-9bd78ff1-c2fb-4b4a-9ae7-995c6833796b.png)

**Comment by NamelessCoder** [comment] 2022-10-21 15:17
Duplicate of https://github.com/FluidTYPO3/flux/issues/1877

**Closed by NamelessCoder** 2022-10-21 15:17 UTC
