### ISSUE TITLE
Using flux field text in a object makes it impossible to create a new object

### ISSUE THREAD

**Issue by dkm-bb** [FluidTYPO3/flux#1481] opened 2017-11-16 08:39 UTC
Hi

I have this flux markup in a content template file.

```
<flux:form.section name="columns" label="Columns">
 <flux:form.object name="column" label="Column">
  <flux:field.input label="header" name="header" />
  <flux:field.text label="Tekst" name="text" />
 </flux:form.object>
</flux:form.section>
```

It seems the <flux:field.text> is causing an issue, since nothing happens when clicking "add Column" - Without the text field, it works as expected.

TYPO3 8.7.8
flux 8.2.1

**Comment by dahaupt** [comment] 2017-11-17 13:23
@dkm-bb I cannot reproduce this issue, running the same version of Typo3 and flux.

Seems to work fine here. Can you provide more information about this?

![image](https://user-images.githubusercontent.com/15915048/32949335-c2950e1a-cba2-11e7-95a5-df10fc44a446.png)

**Comment by dkm-bb** [comment] 2017-11-18 10:29
@dahaupt I remembered that I had extended the class FluidTYPO3\Flux\Form\Field\Text because of a problem with the ckeditor. I had left an echo in my own code. Removing this, solved this error. Sorry for that. This can be closed.

**Comment by dahaupt** [comment] 2017-11-18 12:00
@dkm-bb Nice, you can close it yourself. 👍

**Closed** 2017-11-18 13:08 UTC
