### ISSUE TITLE
[8.7.12][flux:develpoment] non-Admin-User can't access flux:field

### ISSUE THREAD

**Issue by pmuelhaupt** [FluidTYPO3/flux#1540] opened 2018-04-09 09:03 UTC
On development-branch, an editor-user can not see or access any flux:fields

Reproduce:
1. Create a flux-element with one flux:field.input
2. Log in with a non-Admin-User (I gave the user all possible access-rights)
3. Edit the flux-Element. You can not see or access the field.

Interestingly, non-Admin-Users are able to see and access flux:fields inside a flux:form.section. But only these, no other flux:fields are accessable to the user

On master-branch, it works as expected

**Comment by NamelessCoder** [comment] 2018-04-10 09:03
Duplicate of https://github.com/FluidTYPO3/flux/issues/1477, please follow that issue.

**Closed by NamelessCoder** 2018-04-10 09:03 UTC
