### ISSUE TITLE
Problems moving content element in nested fluidcontent element

### ISSUE THREAD

**Issue by heiko-hardt** [FluidTYPO3/flux#1107] opened 2016-03-30 14:49 UTC
Hi, there are some troubles moving content elements in fluidcontent element if nested in workspace mode.
![nested](https://cloud.githubusercontent.com/assets/2315719/14145921/077f3d0e-f696-11e5-886b-4f2ff86eb14e.gif)
Moving the header "Urlaub" into "subelement"."Rechts" is not possible.
Furthermore it looks like that there are some differences using the right workspace-type:
The parent "element" (id:121101) is type of "INITIAL PLACEHOLDER"
The nested "subelement" (id:121104) is type of "First draft version"

While debuging i noticed that the method: 
\FluidTYPO3\Flux\View\PreviewView::registerTargetContentAreaInSession($contentElementUid, $areaName) 
will be called 3 times (id: 121101, 121104, 121103) after moving.
Looks verry strange, hope somebody can help ;-)

kind regards
Heiko

**Comment by NamelessCoder** [comment] 2016-04-11 00:10
Possibly / very likely duplicate of any number of currently open issues describing this same symptom in various ways. Will try to merge those issues somehow.

Side note about the registerTargetContentAreaInSession calls: we expect one call for each nested content area that gets displayed on the page in question. The reason for this call is to store a reference with additional payload information which is impossible to store otherwise (due to it having to be put into a pretty specific DOM ID formatting that then gets parsed by TYPO3 - this *is* bound to change but the workaround is currently required).

**Closed by NamelessCoder** 2016-04-11 00:10 UTC

**Comment by NamelessCoder** [comment] 2016-04-11 00:18
See https://github.com/FluidTYPO3/flux/issues/961 for more details - please follow the issue there!
