### ISSUE TITLE
All plugins flexforms do not show up in backend when editing a plugin

### ISSUE THREAD

**Issue by itekne** [FluidTYPO3/flux#1936] opened 2022-04-01 04:03 UTC
TYPO3 10.4.26
FLUX 9.5.0

Hello,

Since I pulled the commit dev:development#ae4142d, Flexforms in all plugins are not displayed.
No error log, just what the screenshot shows :

<img width="546" alt="Capture d’écran 2022-03-31 à 18 00 14" src="https://user-images.githubusercontent.com/309381/161192556-e213f25d-9c54-4374-acc2-caa75ae4a04f.png">

Resolved by downgrading to fluidtypo3/flux:dev-development#3cc50474d8504bbbf2b043410b04110882332b69

Thank you

**Comment by fiedomedia** [comment] 2022-04-01 08:51
The error is caused by this commit: #ae4142d4c2a7fd9ecacfd2a20ee8ecf4aa707321

**Comment by supercaccia** [comment] 2022-04-01 09:11
I confirm the problema and that worng commit is #ae4142d4c2a7fd9ecacfd2a20ee8ecf4aa707321 .

The problem is in the file: Classes/Integration/HookSubscribers/DynamicFlexForm.php, if you restore only this file all works.

**Comment by supercaccia** [comment] 2022-04-01 13:30
If in te file Classes/Integration/HookSubscribers/DynamicFlexForm.php you replace 

`return static::DUMMY_SOURCE;`

with

`return[]`

it seems to work.

The only thing not correct is that in the flux contents in the "ContentType options" appears also "sDEF".

![sdef](https://user-images.githubusercontent.com/7404955/161272539-234ab04e-a646-4073-9003-2a65c3a9658f.JPG)

**Comment by kraemer-igroup** [comment] 2022-05-04 09:49
Hello, this seems to be fixed with https://github.com/FluidTYPO3/flux/commit/31a4c1633ec520d373e394bbf2617566fe89a21a 🎉

**Comment by itekne** [comment] 2022-05-04 23:09
Hi @kraemer-igroup,

Thank you very much Andi, I confirm that it's OK for me when reverting to fluidtypo3/flux:dev-development (9.6.1)

Thomas

**Comment by NamelessCoder** [comment] 2022-11-07 14:10
Closing as fixed - thanks for reporting and describing the issue!

**Closed by NamelessCoder** 2022-11-07 14:10 UTC

**Comment by itekne** [comment] 2022-11-14 03:02
Thank you @NamelessCoder ^^
