### ISSUE TITLE
unintuitive behaviour in wizard.suggest

### ISSUE THREAD

**Issue by Lirrec** [FluidTYPO3/flux#1062] opened 2016-01-08 16:10 UTC
I have a strange behaviour with the suggest wizard.
I'm using Typo3 7.6.2 LTS and flux 7.6.0, fluidpages 3.4.0.

This snippet works fine and will list all pages from my pagetree for autocompletion.
```xml
<flux:field.relation size="1" table="pages" name="record" label="navmain">
	<flux:wizard.suggest />
</flux:field.relation>
```

However, if i add the table="pages" to the wizard viewhelper, it will only return pages that are direct children of the root page (id=0).
```xml
<flux:field.relation size="1" table="pages" name="record" label="navmain">
	<flux:wizard.suggest table="pages"/>
</flux:field.relation>
```

If i change the table to tt_content(!) i'm getting all pages will appear again in the autocompletion dropdown ( and only pages, no content elements ).
```xml
<flux:field.relation size="1" table="pages" name="record" label="navmain">
	<flux:wizard.suggest table="tt_content"/>
</flux:field.relation>
```

The Ajax POST Request contains the same parameter "table: 'pages'" in all three cases.

Could someone shed some light on this rather "unintuitive" behaviour?
I would expect to see all pages when using table=pages on the wizard. instead it shows only some limited subset. I tried setting "searchCondition" to 1=1 or an empty value, same result.
Why the wizard returns pages if the table is set to tt_content is beyond my imagination...

I guess this is either a bug or some kind of special case handled in Typo3 core ( or some kind of arcane knowledge which is just assumed to be available to the user ;) ).

**Comment by NamelessCoder** [comment] 2016-04-10 23:42
Duplicate of (rather, will only be solved in the same way as) https://github.com/FluidTYPO3/flux/issues/1060 by linking to official documentation. Will be handled in that issue.

**Closed by NamelessCoder** 2016-04-10 23:42 UTC
