### ISSUE TITLE
 flux:field.text CKEditor

### ISSUE THREAD

**Issue by haraldkrischner** [FluidTYPO3/flux#1391] opened 2017-04-04 18:01 UTC
I use Typo3 ~~8.6.1~~ 8.7.0 with current stable flux & co. I use CKEditor which seems to work okay throughout usual Typo3 CEs. Therefore I created a custom config and load it in my pageTS with `RTE.default.preset = custom`.

The problem is: This config isn't used in my fluidcontent content element:
`<flux:field.text name="text" label="Text" enableRichText="true"/>` shows the CKEditor, but not with my custom classes and stuff. Neither does the argument `defaultExtras="richtext[*]:rte_transform[]" ` help, though I am not sure if this is needed at all for CKEditor to work.
Thanks!

Edit:
I just tried it i simple Flexform-XML somewhere else and the result is the same, so the error seems to be on the typo3 side. If you can confirm this behavior, this ticket might be closed as soon as it is addressed it Typo3.

**Comment by haraldkrischner** [comment] 2017-04-06 14:14
I tracked it down a bit. richtextConfiguration has to be set properly. At least in pure Flexform this does the trick.

**Comment by NamelessCoder** [comment] 2017-04-23 17:37
Duplicate of https://github.com/FluidTYPO3/flux/issues/1388, please continue there if you have any more information to add :)

**Closed by NamelessCoder** 2017-04-23 17:37 UTC
