### ISSUE TITLE
flux:form.data leads to infinite recursion in AbstractFormContainer->get() with TYPO3 7.6

### ISSUE THREAD

**Issue by mrk131324** [FluidTYPO3/flux#1006] opened 2015-11-11 08:43 UTC
Using the ViewHelper `flux:form.data` with TYPO3 7.6 breaks the site with a never terminating recursion in the method `AbstractFormContainer->get()` (l. 119).

So far I was not able to determine the reason for that error. It appears that the children Form Elements a FormContainer always include a FormElement that implements the ContainerInterface (maybe the parent itself is included somewhere).

**Comment by mrk131324** [comment] 2015-11-17 09:49
This error was actually causes by a misconfigured flux form. <f:flux:form.sheet /> was not inside a <f:flux:form />. Maybe such a misconfiguration should throw an exception.

**Comment by NamelessCoder** [comment] 2015-11-17 13:17
The expected result should be that a Form instance is transparently created and assigned in the template (as if you *had* used a `flux:form` tag around it). The Form instance that's created should also be perfectly valid except for lacking an ID meaning it can't use automatic translation and manipulation via TypoScript. Other than that it should be fully functional.

It's possible that this is caused by `getForm` on Providers, which will create new Form instances if they cannot be resolved. If that's the case we have to prevent the recursion rather than throw an error, since Providers without Form instances are also a valid construct.

Throwing an error in the ViewHelper rather than creating the Form instance automatically might be a solution, but it would definitely be a breaking change (one I think is severe enough that we'd need to put a feature flag around it).

**Comment by NamelessCoder** [comment] 2015-12-14 15:58
Hi Martin,

This one is fixed - thanks for reporting and please excuse the delay. Is in `development` branch now and will be in the next TER release.

**Closed by NamelessCoder** 2015-12-14 15:58 UTC
