### ISSUE TITLE
[BUG?]New Content Wizard - FluidContent list are cached once

### ISSUE THREAD

**Issue by rupasix** [FluidTYPO3/flux#1453] opened 2017-08-29 09:50 UTC
I want to achieve multi domain instalation and implement few autonomic themes - different content elements and pages. Problem is that fluidcontent list is cached once at the beginning and no matter where (right now i want 3 different themes) i configure my tx_providerext.view.layoutRootPaths etc. i always see that cached content list. It is possible do refresh Fluid Content list to reflect Typoscript configuration from nearest TS Template?

Typo3 8.7.4
fluidcontent | 5.2.0
fluidpages | 4.1.0
flux | 8.2.1
(all from TER)

ps. Fluid Pages behaves as intended - different templates and tca per TS

**Comment by NamelessCoder** [comment] 2017-08-29 15:49
@rupasix The expected behavior is that the cached pageTSconfig (you can inspect this in the `cache_fluidcontent` table) contains a number of PIDinRootLine conditions which match each of your TypoScript templates. I don't remember this exactly but there may be a restriction that only so-called root TypoScript templates cause such a condition.

I suspect it is this template detection or the inheritance that's causing unexpected results? If you could confirm this against your setup I think you'll find the problem.

**Comment by rupasix** [comment] 2017-08-30 09:19
Hey. Thanks for reply. We've made some internal tests and hmm ... TS template works fine (providerext.view is overwritted), pageTSconfig have 2 PIDinRootline conditions but configurations inside are the same. We've took some screenshots from tsconfig and ts related with pages id:1 and id:6 where we have created TS Templates with "Rootlevel" flag. If you need some more tests/ideas - let me know.
![tsconfig_6](https://user-images.githubusercontent.com/9860558/29864974-8bacb66c-8d74-11e7-9c8c-dc805360b070.png)
![ts_6](https://user-images.githubusercontent.com/9860558/29864977-8bd57f7a-8d74-11e7-84ac-de136735327f.png)
![tsconfig_1](https://user-images.githubusercontent.com/9860558/29864975-8bd2d536-8d74-11e7-973d-6356c7593e73.png)
![ts_1](https://user-images.githubusercontent.com/9860558/29864976-8bd45a0a-8d74-11e7-94b6-f1682fe2aeb5.png)

**Comment by NamelessCoder** [comment] 2017-09-02 23:22
@rupasix I have a hunch about the cause of this one - if you could, please try a patch similar to https://github.com/FluidTYPO3/flux/commit/302e6da938b77750558ff3adf301b857dc6fc84e but put it at the end of this loop: https://github.com/FluidTYPO3/fluidcontent/blob/development/Classes/Service/ConfigurationService.php#L321

It would help save me a bit of time if you could try this one on your precise setup since then I wouldn't have to replicate it ;)

**Comment by rupasix** [comment] 2017-09-11 08:20
@NamelessCoder We've applied that code and sadly nothing changed. Any other ideas?

**Comment by rupasix** [comment] 2017-10-24 08:54
@NamelessCoder Do you have any updates about that issue? Can we help you somehow to speed up fixing it?

**Comment by NamelessCoder** [comment] 2020-01-07 01:55
Closing issue as "won't fix" but more precisely, the root cause of this is a problem in the TYPO3 core which prevents reading the right TS configuration in some contexts, which is caused by ConfigurationManager not being able to determine the correct page UID.

See https://github.com/FluidTYPO3/flux/issues/1671

You may find https://github.com/FluidTYPO3/flux/commit/99e4866ec9021ac75ebaff767fdabc65b69f9c88 appropriate to support the use case of having a limited set of page/content templates available on a specific site. This feature will be part of the next release.

**Closed by NamelessCoder** 2020-01-07 01:55 UTC
