### ISSUE TITLE
Empty {settings} from other Extensions in Frontend

### ISSUE THREAD

**Issue by webdev-pw** [FluidTYPO3/flux#2129] opened 2023-09-01 02:46 UTC
Hello,

I am currently updating a TYPO3 from v9 to v11 that uses flux. From TYPO3 v11 the extension Flux overwrites all settings of other extensions in the frontend.
As soon as I deactivate the flux templates, the other extensions work again.

**Comment by sdelcroix** [comment] 2023-09-02 16:40
What version of Flux do you use ?

Do the other extensions inject ConfigurationManager ?

**Comment by webdev-pw** [comment] 2023-09-03 06:00
Hey @sdelcroix,

i am using Flux 10.0.3.
Yes, the other extensions inject ConfigurationManager e.g. cart & cookieman

**Comment by sdelcroix** [comment] 2023-09-03 09:15
Can you try this to confirm that is the same issue I’ve opened few days ago ( #2126  ) ? :

replace ConfigurationManager by ConfigurationManagerInterface where it’s injected

**Comment by Konafets** [comment] 2023-09-06 09:40
@sdelcroix 

> replace ConfigurationManager by ConfigurationManagerInterface where it’s injected

This works. Tested with Powermail.

**Comment by NamelessCoder** [comment] 2023-09-06 12:46
Duplicate of https://github.com/FluidTYPO3/flux/issues/2126, please follow that issue for status.

**Closed by NamelessCoder** 2023-09-06 12:46 UTC

**Comment by sdelcroix** [comment] 2023-09-07 06:55
@Konafets @webdev-pw Could you test the last development version and confirm that it fixes your issue ?

**Comment by webdev-pw** [comment] 2023-09-10 09:10
@sdelcroix 
Sorry for the late reply. I'm currently on vacation and will test it from September 18th.
