### ISSUE TITLE
"Paste as reference" not working

### ISSUE THREAD

**Issue by monosize** [FluidTYPO3/flux#1305] opened 2017-01-31 08:56 UTC
The Button "Paste as reference in this position" makes now a copy of the element.

```\FluidTYPO3\Flux\Service\ContentService::pasteAfter ``` isn't call anymore.
Inside this method there is a call to ```\FluidTYPO3\Flux\Service\ContentService::createMappingArray``` which does the job with the subcommand 'reference'. Now this methods are unused code.

Formerly it was done in ```postProcessCommand```.
How can we insert this feature again? Shall we create a new ```InsertContentReferenceProvider``` and register it with ```    \FluidTYPO3\Flux\Core::registerConfigurationProvider('FluidTYPO3\Flux\Provider\InsertContentReferenceProvider')``` or is this a core feature, which can be placed in ```\FluidTYPO3\Flux\Provider\AbstractProvider:: postProcessCommand ``` ?

**Comment by NamelessCoder** [comment] 2017-01-31 19:32
The "paste as reference" feature is temporarily disabled and has to be recreated in a way that it supports workspaces. You would be *very* welcome to look into that!

No provider is needed; this is low-level enough that it should simply be put into the TceMain class. There is a caveat, though. The existing "pasteAfter" method's business logic cannot be reused, as it would not work with workspaces - and we need to ensure that the original "copy" operation does not happen and then manually create either a new record or a new versioned content record, depending on whether or not we are in a workspace. After this, ContentService's moveRecord method should be called on the record and the input arguments adjusted so action becomes "move".

When all this is done, "pasteAfter" and perhaps other methods as well, can be deleted.

**Comment by fnagel** [comment] 2017-06-08 13:49
> The Button "Paste as reference in this position" makes now a copy of the element.

Question: is there a way to disable the "reference" button as long it's only a duplicate of the copy button?

**Comment by gessulatgessulat** [comment] 2017-08-17 07:18
This this issue finally solved? Still can't refer a content element.

**Comment by typecat** [comment] 2017-09-11 12:23
@gessulatgessulat You can use a workaround: 
1. Right click on a CE and select "copy"
2. On the target page add the CE shortcut
3. There click the button "Insert 1 record(s) from the clipboard" (appears beneath the folder symbol)

**Comment by NamelessCoder** [comment] 2018-07-08 18:43
"Paste as reference" will not be brought back, sorry for the inconvenience. The tiny guide posted by @typecat is pretty much the perfect solution which has only one or two extra steps compared to having a dedicated button.

**Closed by NamelessCoder** 2018-07-08 18:43 UTC
