### ISSUE TITLE
flux.grid with workspaces duplicates content on drag and drop

### ISSUE THREAD

**Issue by onigunn** [FluidTYPO3/flux#1160] opened 2016-06-30 13:21 UTC
### Used Versions

TYPO3 6.2.25
Flux 7.2.3
Workspaces 6.2.0
### Problem

Drag and drop of Content Elements into a flux content type with flux.grid duplicates moved element after reloading backend when you are in a preview workspace.
### How to reproduce
1. switch to preview workspace
2. create content element with flux.grid
3. create new text element
4. drag and drop text element into flux.grid element
5. reload page on backend
6. text element occurs now twice: Inside of the flux.grid and on his intial position

If you delete the duplicated element both will be deleted

**Comment by NamelessCoder** [comment] 2016-06-30 15:05
Hi Onur,

Please confirm that this is also an issue on the `development` branch and using at least TYPO3 7.6 - if the problem also exists there we will look into solving it. Officially we no longer accept bug reports for 6.2 compatible versions (7.6 being LTS is our minimum target), but if the bug you describe is either fixed already or you confirm it and it gets fixed, you or another developer can cherry pick the fix and prepare a pull request into our `legacy` branch (which by the way you should be using for 6.2 based projects as that branch receives contributed fixes whereas no new 6.2 compatible TER versions will be created).

If the problem is solved with `development` branch on at least TYPO3 7.6 you should of course close this issue. If it isn't solved in that branch then please add a comment here so we know it also applies to our currently supported versions ;)

**Comment by NamelessCoder** [comment] 2017-01-04 02:35
Solved by recent patches for workspace compatibility.

**Closed by NamelessCoder** 2017-01-04 02:35 UTC
