### ISSUE TITLE
Wrong colPos-ID on related CE's after copy a flux-Grid Element in WORKSPACES

### ISSUE THREAD

**Issue by davidk1982** [FluidTYPO3/flux#1867] opened 2021-02-15 14:06 UTC
Hello i'm on typo3 9.5.23 and i'm using the latest version from FLUX. Backend works fine, every element is registered and i can see all the forms correctly, and also their preview. If i change from LIVE-Workspace (default) to a created Workspace like "Preview", everything seems to be ok. But if i make a copy of the of a flux-grid element, the flux-grid element and there CE's are copied, but only the new flux grid element is schown in preview. The related CE's are lost. I found out that the new CE's contain the colPos ID from the originally copied flux-grid element. This phenomenon does not occur in the live environment. 

When configuring a workspace environment, does anything have to be considered in the case of Flux?

Many Thx for your great work on these extension.

**Comment by mitrovicsinisaa** [comment] 2021-04-12 14:13
I can confirm the same behaviour on TYPO3 v10.4, and latest Flux 9.4.2.

**Comment by davidk1982** [comment] 2021-05-10 09:36
Hi Sinisa,
do you have any idea what is causing the behavior or do you have a solution to how it can be remedied?

**Comment by NamelessCoder** [comment] 2021-12-05 13:31
Hi @davidk1982 / @mitrovicsinisaa - this problem _should_ be fixed in the `development` branch by commit https://github.com/FluidTYPO3/flux/commit/1b6118215cfc27ec526bf55589062326fcc7120a but it would be great if you can confirm that this patch also solves your particular use case!

**Comment by NamelessCoder** [comment] 2023-07-28 11:01
Closing due to lack of feedback, assumed solved by linked commit.

**Closed by NamelessCoder** 2023-07-28 11:01 UTC
