### ISSUE TITLE
Usergroup access rights for "Allowed fluidcontent types" are only saved partially

### ISSUE THREAD

**Issue by sascha-schieferdecker** [FluidTYPO3/flux#1089] opened 2016-03-02 05:05 UTC
TYPO3: 7.6.4
flux: cc384df

While editing a usergroup, you can assign allowed fluidcontent types. After saving, only the first element is selected:

![image](https://cloud.githubusercontent.com/assets/8793359/13451136/7ee1b5c2-e03c-11e5-96bf-57dcc2527997.png)

After saving:

![image](https://cloud.githubusercontent.com/assets/8793359/13451150/9705b022-e03c-11e5-81fb-0316d4c4f15c.png)

This happens regardless you select some elements or all elements.

**Comment by NamelessCoder** [comment] 2016-03-02 12:12
This one should be fixed, but the fix is part of `fluidcontent` so you must update that to the `development` branch as well. Hope that helps :)

**Comment by voodoom** [comment] 2016-03-02 12:48
Experienced the same issue. Fixed with https://github.com/FluidTYPO3/fluidcontent/commit/be1432be1e74740285aad85d868e142e629257d4

**Comment by NamelessCoder** [comment] 2016-03-02 12:52
Thanks Markus for confirming. Since I have this confirmed from a handful of people now including myself I will take the liberty of closing this issue.

**Closed by NamelessCoder** 2016-03-02 12:52 UTC
