### ISSUE TITLE
Copy localized elements

### ISSUE THREAD

**Issue by mkoehler2911** [FluidTYPO3/flux#974] opened 2015-10-27 13:38 UTC
4 bugs found:

TYPO3 6.2.15
flux 7.2.3 latest dev branch
1. I copied a localized element (E) and pasted it into a random position on the same page. The pasted element (P) is at the random position I chose but the in my foreign language the copied element (P-copy) always appears above the localization of my copied element (E-copy) .
2. For preventing bug 1 I copied and pasted my element above the original element. Now, I put my copied element to the right position on the page. If I only drag and drop the copied element the localizations of my copy follow to the right position. If I move other elements above or below my copy the localizations won't follow anymore.
3. I copied a localized element and tried to paste it on another page. I couldn't localize the (localized) element anymore and the localizations won't appear.
4. It's not possible pasting a reference outside a flux container. The icon is missing.
   ![bildschirmfoto 2015-10-27 um 14 33 33](https://cloud.githubusercontent.com/assets/6328720/10759477/ba493538-7cb7-11e5-96a3-bed74fd46d06.png)
   At the top of my page only the paste symbol appears.

Any solutions for these bugs?

**Comment by BenjaminBeck** [comment] 2015-10-27 14:16
hi mkoehler2911
i can confirm bug 1.
attached is a screenshot showing the result of pasting a localized element after the first element on a page:
![image](https://cloud.githubusercontent.com/assets/1185872/10760587/8a36a758-7cbd-11e5-8cce-e613ca4838c1.png)

**Comment by robsonrobi** [comment] 2015-10-27 14:34
I can confirm that bug and i recognized the following:

 - Copy an element in the original language and create a reference under it
 - In the localized language the reference is NO reference of the localized item, instead it is a new item

Please help us!

**Comment by mkoehler2911** [comment] 2015-10-27 14:45
Had the same bug as @robsonrobi and found strange behaviour of the localized "non"-reference elements.

- I copy an element and paste it as a reference above my original element (localization of my reference appear but it's no reference)
- I move the reference to any random position of my page (localization will move to the random position too)
- BUG: the localization is at two positions of my page (I've 2 elements with the same uid on my page - it's visible in my frontend and if I look up the relations of my page I can find the second localization. The localization is above my localized copied element and at the random position I moved the reference)

**Comment by mkoehler2911** [comment] 2015-11-04 08:23
Something new?

**Comment by fnagel** [comment] 2017-09-18 14:47
I can confirm issue 1) in TYPO3 8.7.4, seems to be related to #1397

**Comment by NamelessCoder** [comment] 2017-09-19 14:23
@fnagel If you have ideas how to solve this, or can help with #976, that would be very appreciated!

**Comment by NamelessCoder** [comment] 2018-07-08 18:46
Solved as part of https://github.com/FluidTYPO3/flux/pull/1563, will be included in release 9.0. Please see the PR for more details, among other things about how to use the migration script.

* The paste as reference feature will not be restored. See https://github.com/FluidTYPO3/flux/issues/1305

**Closed by NamelessCoder** 2018-07-08 18:46 UTC
