### ISSUE TITLE
[BUG] No FCE´s on root page - No Tabs visible

### ISSUE THREAD

**Issue by grimmcreative** [FluidTYPO3/flux#1590] opened 2018-07-19 08:37 UTC
Tried with latest Dev Version of Flux.
No FCE Tabs visible on root page but only if root page has ID1.

Could be related to https://github.com/FluidTYPO3/flux/issues/1574

**Comment by NamelessCoder** [comment] 2018-07-19 08:49
I've tested with 8.7 and 9.3, with root pages having ID=1, but I am not able to reproduce this. Could there be other differences, for example does this happen only with a particular page template selected, are you using the `content_defender` extension, or did you configure a whitelist of allowed CType values in `allowedContentTypes`?

**Comment by grimmcreative** [comment] 2018-07-19 09:41
Hello Claus, 
no `content_defender` is used.
I haven´t defined any `allowedContentTypes` or similar, even did not know about it.

**Comment by grimmcreative** [comment] 2018-07-19 11:39
Update: If i just create a TEXT-CE i can switch to a FCE by Option Menu.

**Comment by grimmcreative** [comment] 2018-07-25 08:54
Same issue again. Complete new installation with FLUX 9.0.1
If Siteroot = ID1 no FCEs are shown (No Tabs just the basic ones).

**Comment by grimmcreative** [comment] 2018-07-25 10:56
Hi Claus, i finaly found it.
The issue comes from cs_seo Extension
TsConfig PID
```
basic.tsConfigPid (Ganzzahl)
1
The Pid where the pageTsConfig is set to extend records
```

If this value here is on 1 - no FCEs - if i set it to 2 - FCEs are shown on root page.

**Comment by NamelessCoder** [comment] 2018-07-25 20:35
I'll close this one - if you find there's something that needs to be changed in Flux, just let me know and I'll reopen :)

**Closed by NamelessCoder** 2018-07-25 20:35 UTC
