### ISSUE TITLE
"ALL Languages" content elements not rendered

### ISSUE THREAD

**Issue by jgreiner** [FluidTYPO3/flux#1605] opened 2018-08-14 15:09 UTC
- typo3 8.7.18
- flux 9.0.1
- fluidcontent dev-development

If I set a fluidcontent CE to "all languages" ist is not rendered in the frontent. If I set it to my default language it is rendered.

I did not have this behavior with flux 8.2.1

**Comment by glucka** [comment] 2018-08-17 13:13
Hi @jgreiner Try to uninstall fluidcontent. With the newest flux do you don't need it.

**Comment by NamelessCoder** [comment] 2019-04-24 11:09
I did a cursory check in Flux and it uses only core methods to render content.

There are three possible situations specific to a FluidTYPO3 context:

1. The content you render is rendered in a Flux column and you use `flux:content.get` or `.render` to do the rendering, in which case, if this fails you have to look for the cause in TYPO3's normal content rendering logic. Specifically, we use `RECORDS` cObject which reads various language settings. But this would mean the problem is outside Flux.
2. The content you render is rendered through a standard page using TS, e.g. `styles.content.get` in which case the TS configuration would be the culprit - and this would also be outside Flux.
3. You render the content with VHS using `v:content.get` or `.render` in which case this may be a FluidTYPO3 issue - but one that has to be reported for VHS's bug tracker instead.

Perhaps items 1 and 2 are enough for you to locate the problem. There is no reason why an "all languages" element from Flux would not render if other ones render just fine.

I'll take the liberty of closing this issue. If you find the problem is with VHS (in which case *any* CType would behave the same) please open a new issue on https://github.com/FluidTYPO3/vhs/issues (describe the problem with a core-native CType so it's clear it isn't Flux).

**Closed by NamelessCoder** 2019-04-24 11:09 UTC
