### ISSUE TITLE
Version 9.6.x - Upgrade Wizard fails - AbstractUpdate not found

### ISSUE THREAD

**Issue by secured** [FluidTYPO3/flux#1969] opened 2022-06-30 07:03 UTC
On the latest TYPO3 Version 10.4.30 the Upgrade Wizard fails.

[CRITICAL] request="e383330f5eec2" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'TYPO3\CMS\Install\Updates\AbstractUpdate' not found | Error thrown in file /var/www/html/public/typo3conf/ext/flux/Classes/Updates/MigrateColPosWizard.php in line 28.

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.5/Deprecation-86366-MethodsInAbstractUpdate.html

It looks like the function got deprecated early. On Version 10.4.27 this functions is still available.

**Comment by rintisch** [comment] 2022-07-04 09:13
There is already a solution in the development branch:
 https://github.com/FluidTYPO3/flux/commit/61a2c281571af45a81d924433212682bb62abb4c

**Comment by cweiske** [comment] 2022-07-14 06:25
Duplicate of #1934.

**Comment by NamelessCoder** [comment] 2022-10-17 12:22
Closed as solved/duplicate.

**Closed by NamelessCoder** 2022-10-17 12:22 UTC
