### ISSUE TITLE
Localization Bugs - wrong position - moving -> lost

### ISSUE THREAD

**Issue by robsonrobi** [FluidTYPO3/flux#886] opened 2015-08-11 12:33 UTC
Currently we are working with TYPO3 7.4 and are using are development versions of, flux, fluidcontent and fluidpages. Localization is not working correctly.
I created 2 text elements and then translated them. Everything ist fine. Addding a third text element at the bottom, localization results in a different position (in the middle). Than, trying to move the third text element to the bottom it gets lost. It was moved inside the Fluid Content Area, but there is no area.

![01_translate_2_text_elements](https://cloud.githubusercontent.com/assets/3888860/9197599/c9caba2c-4035-11e5-8289-634ace265fed.png)
![02_result_translating_two_tex_elements](https://cloud.githubusercontent.com/assets/3888860/9197604/cda8f9e2-4035-11e5-9455-aee0a33a3db4.png)
![03_translate_text_three](https://cloud.githubusercontent.com/assets/3888860/9197605/d0f1e0dc-4035-11e5-99d3-99bf9d804cbe.png)
![04_result_trnalsate_text_three](https://cloud.githubusercontent.com/assets/3888860/9197608/d3c5c468-4035-11e5-82f6-d90d18386ab1.png)
![05_moved_text_three_to_bottom](https://cloud.githubusercontent.com/assets/3888860/9197612/d6ae8016-4035-11e5-8129-e6121ac71257.png)

**Comment by DenisMir** [comment] 2015-08-13 13:58
I can confirm this bug with Typo3 6.2.14. I have got some nested content elements on my default language page. Then I added the new language overlay and copied the content which worked fine. Then I added a simple content element to the default language and copied it over to the new language. The content element got copied to the first position in the new language. Then I moved nested content element above the added content element and the result was that the nested content element disappeared. This bug makes working with a translated site impossible.

**Comment by robsonrobi** [comment] 2015-08-13 13:59
Yes, it is a bit disappointing, because localization is one of the biggest features typo3 comes along.  :-(

**Comment by DenisMir** [comment] 2015-08-13 14:01
The problem gets even worse that with every flux release other parts of the translation stuff do not work. I have not found a combination of fluidtypo3 extension combination which does work stable. (without some major bugs in that area)

**Comment by eckonator** [comment] 2015-08-14 11:15
I like flux and hope the bug will be fixed quickly.

**Comment by robsonrobi** [comment] 2015-08-14 11:18
We all love FLUX and i hope, someone can help soon. Great job so far, but localization is so needed.

**Comment by DenisMir** [comment] 2015-08-19 13:42
The reason for this bug is that the element which is positioned in the typo3 main column should have `colPos=0` but gets `colPos=18181` during the movement process. This leads to the "lost" content. An easy workaround is to set the `colPos` manually to `0` which makes the content element and all its children visible again.

**Comment by robsonrobi** [comment] 2015-08-19 14:07
It is easy for an developer, but our people who generate content and use the cms it is not really a solution..

**Comment by DenisMir** [comment] 2015-08-20 05:59
@robsonrobi I know that. :+1:

**Comment by robsonrobi** [comment] 2015-08-20 07:06
We are looking forward to a fix. As eckonator and myself said, FLUX is great!

**Comment by NamelessCoder** [comment] 2015-09-13 12:52
A patch for this should be coming any day now, courtesy of @galoppi whose work we greatly appreciate ;)

**Comment by robsonrobi** [comment] 2015-09-13 13:12
That would be awesome!!! Thank you so much!

**Comment by DenisMir** [comment] 2015-09-13 14:41
Awesome. I'm looking forward testing the improvement.

**Comment by eckonator** [comment] 2015-09-13 15:10
Very good News! Thanks for your work :)

**Comment by NamelessCoder** [comment] 2015-09-19 22:41
Should be fixed - expecting new TER release tomorrow. If you test this on development or using next TER release and there still are issues and those issues don't appear in this list:

https://github.com/FluidTYPO3/flux/pull/921

... then please either report here or in a new issue! Thanks for the patience guys.

**Closed by NamelessCoder** 2015-09-19 22:41 UTC
