### ISSUE TITLE
flux:field.inline.fal and filemetadata

### ISSUE THREAD

**Issue by NikoHerth** [FluidTYPO3/flux#2113] opened 2023-08-03 15:14 UTC
When using flux:field.inline.fal it is possible to set element specific values for "Alternative Text" and "Description (Caption)".
The default values for those fields are taken from the sys_file_reference of the default language.
But when the metadata for a file are already translated, the translation isn't used as the default values.

I wonder if it's a core topic as the untranslated defaults are shown in the backend or if it's related to flux.

Maybe you can provide some insights.

Versions used: 
TYPO3 11.5
flux 9.7.4

**Comment by NamelessCoder** [comment] 2023-08-04 12:38
Backend's usage of incorrect values would be a core issue, not a Flux issue. Flux only delivers the DS, not the data.

**Comment by NamelessCoder** [comment] 2023-08-14 14:06
Re-tested on TYPO3v12. File references' default values are taken from the translated version of file metadata. Overriding properties in the reference also works. Closing as "cannot reproduce" and "possible core issue or problem with third party file resolving logic".

**Closed by NamelessCoder** 2023-08-14 14:06 UTC

**Comment by NikoHerth** [comment] 2023-09-01 09:22
Sorry for the late reply. I investigated a bit further now:

The usage of sys_file_metadata works, as long as the name of the flux:field.inline.fal-field is "image". When I change the field name to e.g. "myimage", the sys_language_uid field in sys_file_reference is always set to 0 during the translation process. This causes the title and description field of the file to be shown in the default language instead of using the translation from sys_file_metadata.

The (not working) field definition is

<flux:field.inline.fal name="myimage" label="file" transform="filereference" />

sys_file_reference shows
tablenames: tt_content
fieldname: myimage
sys_language_uid: 0

where sys_language_uid should be set to the corresponding language.

Do I miss an additional configuration to get the individual fieldname to work?

**Comment by NamelessCoder** [comment] 2023-09-01 12:43
@NikoHerth if this works with a field named `image` but doesn't work with a field named `myimage` then that's one more indication that this is in fact a core issue - not a Flux issue. As already mentioned, Flux does literally nothing regarding pulling, presenting, translating or otherwise adapting the _data_; Flux only tells the core "here's a FAL field, please render it and process it like an IRRE FAL field".

The field name having an effect tells me that this is about how the TYPO3 core handles the FAL references and likely is also about how the core does this within context of a FlexForm. There *is* a non-FlexForm field named `image` on `tt_content` and from your description, it appears the core is resolving *that* field's definition instead of the FlexForm field's definition - and therefore coincidentally makes it work in FlexForm context as long as the field name is the same as a non-FlexForm, IRRE FAL field in the table. I would then also expect that naming the Flux field `assets` would also cause it to work, coincidentally.

> Do I miss an additional configuration to get the individual fieldname to work?

No, I don't think there's anything you or I can do from the implementation or user side. This has to be reported to the TYPO3 core for them to investigate and eventually fix.

https://forge.typo3.org/projects/typo3cms-core/issues
