### ISSUE TITLE
Page Configuration - Tab label "options" is not translated

### ISSUE THREAD

**Issue by demacrocom** [FluidTYPO3/flux#1057] opened 2016-01-06 13:19 UTC
flux version 7.2.3

In line 96 of EXT:flux/Classes/Form.php there is this string:
LLL:EXT:flux/
It's extended by $this->localLanguageFileRelativePath resulting in a string with a double slash ("//") after the word "flux". This causes the translation to fail, because the file can't be found.

To reproduce:
Edit a page, switch to tab "Page Configuration" and have a look at the labels inside the sections "Page Configuration" and "Page Configuration - subpages". They show up as "options" instead of "Options" which would be the translation from locallang.xlf of flux extension.

Fix: remove the "/" after "flux" and translation will work just fine. The tab label in Page Configuration will change from "options" to whatever is given in the translation file.

**Comment by NamelessCoder** [comment] 2016-01-06 14:21
@demacrocom are you by any chance on a Windows system? Not that I'd call that the cause - just looking for a reason why it has not been reported before.

**Comment by demacrocom** [comment] 2016-01-06 15:14
No M$ products in sight :)

I guess the issue isn't of great importance to most users, though it exists for a long time. "options" is quite a speaking description. And really: who cares if it's capitalized or not ;)
To be honest: I only reported it, because it's more or less just a typo. If it was a complex thing, I wouldn't have bothered you, too.

**Comment by NamelessCoder** [comment] 2016-04-10 23:41
Fixed by recent commit removing additional slash.

**Closed by NamelessCoder** 2016-04-10 23:41 UTC
