### ISSUE TITLE
don't name your sheet options -> doc issue

### ISSUE THREAD

**Issue by wikipeter** [FluidTYPO3/flux#1021] opened 2015-11-16 16:53 UTC
Hi folks,

In my opinion there should be a big hint, marked red that a developer is not allowed to name one of his sheets "options", as options is kinda reserved sheet name. Otherwise you get an memory allocation error.

I can remember this was an issue in the past, then it worked, now it stopped working. Not sure if by mistake or not, but at least the documentation should mention it.

this is not really a code issue (I think) as I am facing this in a 6.2 (no) LTS (anymore) project.

Cheers,
Peter

**Comment by NamelessCoder** [comment] 2015-11-16 21:23
Hi Peter,

Are you sure this still happens with Flux? For quite some time it should be possible to "reuse" sheets by creating new ones with the same name as existing ones. Doing so should just add any fields etc. inside the clone to the original sheet with the order determined by the order of components in the template.

**Comment by wikipeter** [comment] 2015-11-17 12:44
Hi Claus,

I was facing this behaviour yesterday. But as already mentioned, this is a TYPO3 6.2 setup and I am forced to use not the latest version of flux, but rather f02ee02 (last 6.2 compatible commit) with a patch from 71ce237 regarding localization issues of page properties.

I had several FCEs declaring flux:form.sheet name="options" which caused a memory allocation error / Error 500.

After i refactored (basically just removed the individual "options" sheet declaration) the related elements, the error was gone.

**Comment by NamelessCoder** [comment] 2015-11-17 12:53
Ah okay - thanks for explaining :)

In that case there's just one thing to do: we have created a `legacy` branch where we split off the last point supporting 6.2 - and we don't maintain this ourselves, but we don't mind merging pull requests that are made to that branch. So, if there's a patch you require on for example multiple sites or wish to contribute back to other users stuck with 6.2 for a while, you can clone the repository, make a branch based on `legacy`, cherry-pick the patches you require (and resolve conflicts if they occur) and publish that as a new pull request. At some point you may run into code that can't be cherry-picked and may have to create manual patches with those fixes - we will also gladly accept those, but I expect they get somewhat lower priority if there's commit format or CGL concerns ;)

If you do need to investigate a manual patch for this: I suspect this is caused by the `get()` method on the Form class not returning the expected sheet - or the ViewHelper not yet attempting to use `has()` and `get()` on the `$form` variable to detect an existing sheet. All code around these points should work properly also in the legacy version.

I'll close this issue as it doesn't seem to be a problem in the latest development branch or most recent TER release.

**Closed by NamelessCoder** 2015-11-17 12:53 UTC
