### ISSUE TITLE
flux:wizard.edit uses/generates wrong edit link.

### ISSUE THREAD

**Issue by samowitsch** [FluidTYPO3/flux#1292] opened 2017-01-18 08:39 UTC
I am try to use flux:wizard.edit with flux:field.multiRelation or flux:field.relation in my FCEs. The relation itself works, the edit button appears but the edit link of the button is wrong:

.../typo3/index.php?route=/record/edit&token=0ddaaa0a550a3f66715bb0f65172c8c93f625bc6&**edit[tt_content][22844]**=edit&returnUrl=/typo3/index.php?M=web_layout&moduleToken=59a485eca41129d0f137b293a6db3c075d6b5664&id=235#element-tt_content-22844#

In any case the edit link goes to edit[tt_content][current_edited_fce_uid] and not in my case edit[tx_my_custom_table][selected_uid].
If i click on it for short a popup opens and closes immediately again (when i copy this link and open it manually in a separate tab/window the link is working) ?
The used table (custom tables, pages) makes no difference.

```
<flux:field.relation name="foo" label="Label" table="tx_customtable">
    <flux:wizard.edit label="Edit" width="600" height="400" />
</flux:field.relation>

or

<flux:field.multiRelation name="foo" label="Label" table="tx_customtable">
    <flux:wizard.edit label="Edit" width="600" height="400" />
</flux:field.multiRelation>
```
Used versions:
TYPO3 7.6.14
flux 7.4.0
fluidcontent 4.4.1
fluidcontent_core 1.4.0
fluidpages 3.6.1
vhs 3.0.1

**Comment by NamelessCoder** [comment] 2017-01-19 11:50
This is almost certainly not a problem caused by Flux but rather a bug in the FormEngine. As with every other component, Flux does not render HTML but delivers a TCEforms array which is then rendered by FormEngine. In the case of this edit wizard, there is no UID involved; it should be taken from the field value when you click the button, so I suspect it is this JS "retrieve value" logic that isn't working.

I'll take a little risk and close this issue, referring to the TYPO3 core bug tracker instead.

**Closed by NamelessCoder** 2017-01-19 11:50 UTC

**Comment by samowitsch** [comment] 2017-01-20 09:29
@NamelessCoder thx for feedback. What i need in TCA style looks like this:
```
			'config' => array(
				'type' => 'select',
				'foreign_table' => 'tx_playground_domain_model_lorem',
				'foreign_field' => 'foo',
				'maxitems' => 2,
                'wizards' => array(
                    'edit' => array(
                        'type' => 'popup',
                        'title' => 'LLL:EXT:lang/locallang_tca.xlf:be_users.usergroup_edit_title',
                        'module' => array(
                            'name' => 'wizard_edit',
                        ),
                        'popup_onlyOpenIfSelected' => 1,
                        'icon' => 'actions-open',
                        'JSopenParams' => 'height=350,width=580,status=0,menubar=0,scrollbars=1'
                    ),
                    'suggest' => array(
                        'type' => 'suggest',
                        'default' => array(
                            'searchWholePhrase' => 1
                        ),
                        'tx_playground_domain_model_lorem' => array(
//                            'searchCondition' => ''
                        )
                    )
                ),
			),
```
how can i get the same result with flux? flux:field.select has no options for foreign_table and so on?
and when i use flux:field.relation or flux:field.multiRelation the edit button doesn't work. I tried different combinations with no success.
