### ISSUE TITLE
flux:content.get with render = false does not translate the record

### ISSUE THREAD

**Issue by mrk131324** [FluidTYPO3/flux#1030] opened 2015-11-20 17:06 UTC
When using the flux:content.get view helper with argument render = false is responds with the record untranslated. With render = true it uses the cObj RECORDS to take care of translation overlay (which is smart). 

Furthermore the record is returned as array, not as a object. This is a common problem of TYPO3fluid view helpers, that they do not respond with objects. Given that some of the core fluid view helper rely on objects it lead to a lot of tedious conditions in the templates. By now we should assume that all records have an extbase domain object and repository. These can also take care of proper translation overlays.

**Comment by mrk131324** [comment] 2015-11-20 17:07
The code in question can be found here:
`Classes/ViewHelpers/Content/GetViewHelper.php:132ff`

**Comment by NamelessCoder** [comment] 2017-10-30 01:19
Oops - this one was actually fixed a good while ago, but the issue was not closed along with the solution. We are now using ContentObjectRenderer->getRecords() to read records, which is what RECORDS also uses, so in the next version of Flux the following will be true: if the problem isn't fixed by switching to getRecords(), this bug will need to be reported to the TYPO3 core bug tracker. In both cases, Flux will be in the clear - which is why I will close this issue.

Regarding returning arrays or objects: returning an object (I assume you mean a domain object) would require a domain model for content, which does not (yet) exist in TYPO3. So it is not feasible to return a specific object type for each record. If you meant the array of records and expected for example a QueryResult or ObjectStorage the reasoning is similar, e.g. that this implies a domain object for content. It wouldn't make much sense if you expect a standard Iterator that contains records as arrays - since no ViewHelpers explicitly require that type, it isn't compatible with QueryResult or ObjectStorage, and the ViewHelpers from for example VHS transparently support either arrays or Iterators - which would make the point moot (arrays would be just fine).

> By now we should assume that all records have an extbase domain object and repository.

I am writing this two years after you wrote that comment. TYPO3 still has no such repository or model - not even in dev-master. That's just to say I definitely wouldn't assume that all records, and in particular the core ones, have associated models. Among other things, extending model properties is a big concern to which there's still no (acceptable) solution.

**Closed by NamelessCoder** 2017-10-30 01:19 UTC
