### ISSUE TITLE
[BUG?][TYPO3-7.6.16] Problem with flux:field.file in page configuration and inheritance

### ISSUE THREAD

**Issue by VincentKoehler** [FluidTYPO3/flux#1395] opened 2017-04-18 12:46 UTC
My setup:
Typo3 7.6.16
fluid 7.6.0
fluidcontent 5.1.0
fluidcontent_core 1.4.0
fluidpages 4.1.0
flux 8.1.0

I created a page template with the option to add a logo. All subpages should be able to inherit the logo, unless overwritten. So I added this flux field to the page configuration:

`<flux:field.file name="settings.subpagelogo1" allowed="jpg, jpeg, png, gif, svg" required="0" maxItems="1" showThumbnails="1" label="Logo rechts oben - 1 (z.B. Kliniklogo)" />`

This works well as long as I don't activate inheritance, but as soon as I do two problems occur.

For instance, I have created a page with a logo for the page itself and all sub pages. Now if I create a suppage for this page, it's backend looks like this:
![flux-file-problem](https://cloud.githubusercontent.com/assets/19953138/25131117/e16aa404-2444-11e7-8e6b-ff6bd98ad86b.jpg)

I can solve this by overwriting the logo of the subpage, but of course that's not the purpose of the inheritance. Also I'm not able to unselect the logo by using the trashcan button.

Am I doing something wrong or is this a bug? Thanks in advance!

**Comment by TheNaderio** [comment] 2017-04-18 20:22
Your Flux Column has: slide="-1" ?

**Comment by VincentKoehler** [comment] 2017-04-18 22:19
Not sure what you mean. Flux columns have a slide attribute? My column looks like this:

`<flux:grid.column colPos="0" colspan="1" name="main" />`

**Comment by TheNaderio** [comment] 2017-04-19 14:15
add `slide="-1"` to your column: `<flux:grid.column colPos="0" colspan="1" name="main" slide="-1" />`.
the content of the column will be inherited to all pages under this page.

**Comment by VincentKoehler** [comment] 2017-04-25 07:26
Sorry for the late reply and thanks for your suggestion. Add slide="-1" causes a 'Argument "slide" was not registered" exception. Also wouldn't this only affect content in the columns and not page configuration fields?

**Comment by spfeifer** [comment] 2017-06-14 13:01
Got the same Issue in TYPO3 7.6.16 with Flux 7.4.
I created a page configuration in a page template like this:

```
<f:section name="Configuration">
        <flux:form id="contentPage">
            <flux:field.file name="settings.logo" allowed="jpg,png,svg" showThumbnails="1" label="Logo" />
            <flux:grid>
                <flux:grid.row>
                    <flux:grid.column colPos="0" name="content" label="Content" />
                </flux:grid.row>
            </flux:grid>
        </flux:form>
</f:section>
```

The content slide does work properly, until you open the page configuration on a sub-page and save it. After that, the select field is filled with something like "logo.pngfileadmin%2Fuser_upload%2Flogo.png" instead of an empty value.

**Comment by NamelessCoder** [comment] 2017-07-04 21:27
Can this be confirmed on TYPO3 8.7 / Flux 8.2+? If the problem does not exist there it has been patched either in TYPO3 or Flux since then. If it is fixed in TYPO3 but was not backported you may ask for a backport on the TYPO3 core issues tracker - if it is fixed in Flux we depend on you users to locate the fix and create a PR with a cherry-pick to the `legacy` branch.

In the case this can be confirmed on TYPO3 8.7 and Flux 8.2+ (current supported versions) we can do something about it. Side note: the inherited value gets set as `default` in the TCA we return, so if this doesn't work with normal TCA components in the use case you describe, then we can't make it work in Flux (and you'll need to look for another component which does support default values such as those in your use case).

So please give this one a check in TYPO3 8.7 since we no longer support 7.6.

**Comment by samowitsch** [comment] 2017-08-03 07:49
Typo3 8.7.4
fluid 8.7.4
fluidcontent 5.2.0
fluidcontent_core 1.4.0
fluidpages 4.1.0
flux 8.2.1

![inheritance_ flux_field_file](https://user-images.githubusercontent.com/2334402/28911481-f234bafa-7830-11e7-93b2-3d7a256a6c32.png)

**Comment by develth** [comment] 2017-11-23 11:23
Are there any news on this?

**Comment by develth** [comment] 2017-11-23 12:06
Classes -> Form -> File.php

Replace function setDefault with 

    /**
	 * Overrides parent method to ensure properly formatted
	 * default values for files
	 *
	 * @param mixed $default
	 * @return \FluidTYPO3\Flux\Form\FieldInterface
	 */
	public function setDefault($default) {
		/*if (NULL !== $default) {
			$files = array();
			$filePaths = GeneralUtility::trimExplode(',', $default);
			foreach ($filePaths as $path) {

				if (FALSE === strpos($path, '|')) {
					$files[] = $path . '|' . rawurlencode($path);
				} else {
					$files[] = $path;
				}
			}

			$default = implode(',', $files);
		}*/
		$this->default = null;
		return $default;
	}

solves it for me.

**Comment by samowitsch** [comment] 2017-11-23 12:53
+1 yes this works.

**Closed** 2018-07-08 19:40 UTC
