### ISSUE TITLE
flux:form.section – Section Contents not shown in header on Firefox

### ISSUE THREAD

**Issue by frpuser** [FluidTYPO3/flux#1987] opened 2022-08-23 13:44 UTC
**Bug:**
When I open a content element that uses flux.sections, there are no titles in the individual "tabs". If a single tab is opened and closed once, a title is visible in that tab (content of the tab).
This problem seems to be browser dependent. I could only see this problem in Mozilla Firefox, in Google Chrome it work properly.

**Environment:**
TYPO3: 11.5.14
Flux:  9.6.1
Tested Browser: 
   - Mozilla Firefox 91.12.0esr (64-Bit) (on Windows)
   - Mozilla Firefox 103.0 (64-Bit) (on Mac)

**Screenshot of the Problem:**
<img width="690" alt="Bildschirmfoto 2022-08-23 um 14 28 10" src="https://user-images.githubusercontent.com/20813220/186158914-9455ef29-be41-4b7a-b730-61a292303e2b.png">

**Flux Configuration:**
```
<f:section name="Configuration">
<flux:form options="{group: 'FCE', icon: 'EXT:frp_fce/Resources/Public/Thumbnails/module_contentslider.png'}" id="contentslider">
	<flux:form.sheet name="slider">
		<flux:form.section name="slides" label="slides">
			<flux:form.object name="default">
				<flux:field.input name="caption" maxCharacters="55" required="1"/>
				<flux:field.input name="title" maxCharacters="30" required="1"/>
				<flux:field.input name="subtitle" maxCharacters="55" required="1"/>
				<flux:field name="link" label="link" type="input" config="{
                        			renderType: 'inputLink'
                    		}" />
                    		<flux:field.input name="linktext" maxCharacters="55" required="1"/>
                    		<flux:field type="group"
                        			name="image"
                        			label="Images"
                        			config="{
                            			type: 'group',
                            			internal_type: 'db',
                            			allowed: 'sys_file',
                            			size: '1',
                            			minitems: 0,
                            			maxitems: 1,
                            			show_tumbs: 1,
                            		appearance: {
                                			elementBrowserType: 'file',
                                			elementBrowserAllowed: 'jpg,jpeg,png,gif'
                    			}}" />
				</flux:form.object>
			</flux:form.section>
		</flux:form.sheet>
	</flux:form>
</f:section>
```
[for better readability, flux config also visible in a gist](https://gist.github.com/frpuser/6ab728bfc12ddbf37e7c83d4180370fe)

**Comment by NamelessCoder** [comment] 2022-10-21 15:15
Sorry, but you have to report this to the TYPO3 core bug tracker, https://forge.typo3.org. The problem is not caused by Flux and cannot be fixed in Flux - any implementation of a FlexForm with section+sectionobject (and possibly even root level TCA fields of type inline, I've not tested this) also without Flux would be similarly affected.

**Closed by NamelessCoder** 2022-10-21 15:15 UTC
