### ISSUE TITLE
flux:form.object elements broken in backend if there is no access to the root language

### ISSUE THREAD

**Issue by ulbrich-media** [FluidTYPO3/flux#1877] opened 2021-03-22 10:17 UTC
Hello, 

we encountered a bug with one of our flux based TYPO3 installations. For that multi language page we have editors with restricted access to only their respective language, meaning they don't necessarily have access to the root language. 
In that case they are not able to open the accordion items in the backend generated by the flux:form.object ViewHelper. 

**Way to reproduce** 
1. Have a flux based content element with a flux:form.object field, like e.g. a simple accordion or tabs element. 
2. Create one of those in your root language and translate it to another. It doesn't matter if connected or free mode was used. 
3. Use a backend user which only has access to the second language to open that content element. The accordion for editing the objects won't listen to any events and also doesn't show any of the options, like show/hide, delete. 

This error was tested on the current TYPO3 10LTS Version with flux 9.4.2 installed.

**Comment by NamelessCoder** [comment] 2023-08-09 19:39
Tested and confirmed to still be the case on TYPO3v12. Unfortunately though, this simply appears to be the way TYPO3 itself handles section objects in non-default languages when the user does not have access to the root language. By the way, this is the case whether the content record is a translation or was created directly in the non-default language.

There is a TYPO3 core bug report for this: https://forge.typo3.org/issues/97287

I have to close this issue since there is nothing that I could do in Flux that would solve it.

**Closed by NamelessCoder** 2023-08-09 19:39 UTC
