### ISSUE TITLE
FAL field not working in 7.6.x

### ISSUE THREAD

**Issue by mithri** [FluidTYPO3/flux#981] opened 2015-10-30 09:46 UTC
Hi,

the <flux:field.inline.fal is not working on the current master.

Invalid argument supplied for foreach() in /TYPO3.CMS/typo3/sysext/backend/Classes/Form/Container/InlineControlContainer.php line 171

and this:
Table tt_content field file: If both foreign_unique and foreign_selector are set, they must point to the same field 

I think it has something to do with the new form system? Or is this a Core Bug? Anyone an idea?

Thanks
Tobias

**Comment by jsegars** [comment] 2015-11-02 23:52
It looks like the FormEngine may have gotten stricter on expected TCA definitions. The issue seems to be that foreign_selector has a value but foreign_unique is set with an empty string.  If Flux is patched (in ugly way) to remove foreign_unique it gets past this error and if the core is patched to loosen up the checking in \TYPO3\CMS\Backend\Form\FormDataProvider\TcaInlineConfiguration it also gets past the error.

Of course, I immediately run into another error about missing $tableName when the FAL form is compiled so the ugly patches don't offer much in the way of actual progress :)

**Comment by RauchF** [comment] 2015-11-03 10:01
> Of course, I immediately run into another error about missing $tableName when the FAL form is compiled so the ugly patches don't offer much in the way of actual progress :)

This seems like it may be this core bug: https://forge.typo3.org/issues/70918

It also affects regular FlexForms.

**Comment by NamelessCoder** [comment] 2015-11-03 12:45
Duplicate of https://github.com/FluidTYPO3/flux/issues/759 - please follow it there. It is a core issue and also affects any other type of FlexForm integrations; @cweiske has been kind enough to report it already at https://forge.typo3.org/issues/71239.

**Closed by NamelessCoder** 2015-11-03 12:45 UTC

**Comment by NamelessCoder** [comment] 2015-11-03 12:47
@jsegars Would you mind creating a new issue about the `foreign_*` strictness issues? Those are, as far as I can tell, not related to inline elements relational issues. Thanks :)

**Comment by mithri** [comment] 2015-11-03 13:27
Hi just for clarificiation:

We upgraded from 7.5 to 7.6-master. After that i got the foreign_* problem with the following field:

<flux:field.inline.fal name="file" multiple="1" maxItems="1" label="Hintergrundbild" />

At some point i got the other error, too. But i did not wrap the fal field in any other field.

**Comment by jsegars** [comment] 2015-11-06 04:59
@NamelessCoder Will do.  I'll do a little more testing over the weekend and then get the issue opened.

**Comment by RauchF** [comment] 2015-11-09 15:14
@mithri: Indeed, this ticket is not the same issue as #759, so I guess if you need flux:field.inline.fal, or already have dozens and dozens of CEs with many relations each (not inside sections) the best choice is still 7.5 (or 7.6-dev before the formhandler refactoring) and not 7LTS. At least until the foreign_* issue and even more importantly https://forge.typo3.org/issues/71436 are fixed.
