### ISSUE TITLE
Fluid Content type not selected 

### ISSUE THREAD

**Issue by mkoehler2911** [FluidTYPO3/flux#880] opened 2015-08-07 07:17 UTC
Copy & paste works great! Thanks for fixing this.
Now, I got a small bug with typo3 standard elements (text element in this case).

I get "Fluid Content type not selected - edit this element in the TYPO3 backend to fix this!" in typo3 standard elements. It's a small problem but I can't see the text preview anymore.

Thanks in advance!

**Comment by xf-** [comment] 2015-08-07 07:21
Please provide more informations - TYPO3 version, do you use fluidcontent_core or csc?

**Comment by mkoehler2911** [comment] 2015-08-07 07:25
Sorry:
Typo3 7.1.0
flux: latest development
fluidcontent: 4.2.2 (beta)
fluidpages: 3.2.3 (beta)

**Comment by georg-tiefenbrunn** [comment] 2015-08-07 14:56
Please have a look at https://github.com/FluidTYPO3/fluidcontent/issues/260

**Comment by monosize** [comment] 2015-08-07 19:31
The changes was made in this commit FluidTYPO3/fluidcontent@763fbb612e95038391d178e33295c2829623f738

The problem is, that the default template is used also for non fluidcontent elements.

### Workaround
You can override the templateRootPath with 
```
plugin.tx_fluidcontent {
	view {
		templateRootPaths {
			0 = EXT:YOUR_EXTENI/Resources/Private/FluidContent/Templates/
		}
	}
}
```

and then create a new Index.html template in the Folder `/Resources/Private/FluidContent/Templates/`

```xml
<f:layout name="Content" />
<f:section name="Configuration">
	<flux:form id="default">
		<flux:form.option name="enabled" value="0" />
	</flux:form>
</f:section>

<f:section name="Preview">
	<f:render section="Main" />
</f:section>

<f:section name="Main">
</f:section>
```

**Comment by NamelessCoder** [comment] 2015-08-07 20:06
Duplicate of https://github.com/FluidTYPO3/fluidcontent/issues/260 - fix is committed. Please report in https://github.com/FluidTYPO3/fluidcontent/issues/260 if you still have issues after pulling development branches!

**Closed by NamelessCoder** 2015-08-07 20:06 UTC
