### ISSUE TITLE
form.object with contentContainer="1" throws error when CE is part of an IRRE relation

### ISSUE THREAD

**Issue by apiening** [FluidTYPO3/flux#1700] opened 2019-05-17 20:02 UTC
I use a `form.object` with `contentContainer="1"` in a custom CE to render an accordion with dynamic panels:
```
<flux:form id="accordion">
    <flux:form.section name="panels">
        <flux:form.object name="panel" contentContainer="1">
            <flux:field.input name="title" label="Titel" />
            <flux:field.checkbox name="active" label="Aktiv" />
        </flux:form.object>
    </flux:form.section>
</flux:form>
```
```
<f:for each="{panels}" as="panel" iteration="iteration">
    ... HTML markup ...
    <flux:content.render area="{panel.panel.colPos}" />
    ... HTML markup ...
</f:for>
```
If I put this CE on a page, it works perfectly fine. However if I add it to a model with an inline / IRRE relation to tt_content, It produces the following error:
```
(1/1) TYPO3Fluid\Fluid\Core\ViewHelper\Exception

Argument "column" or "area" for "flux:content.(get|render)" was a string column name "", but this column was not defined
```

I can add all other CEs just fine here and they're rendered without issues. Even custom CEs with `form.content` works fine. But CEs with dynamic content panels based on `form.object` with `contentContainer="1"` does not work.

I have attached a screenshot of the error I get with debug mode enabled in the FE. It shows a part of the call stack and exposes where the error is thrown.

Any idea what may cause this?

**Comment by NamelessCoder** [comment] 2020-01-10 00:37
Hi @apiening,

Did you find the cause for this one? It looks from the error message as if the variables are not assigned to the template before it gets rendered - error indicates `{panel.panel.colPos}` is an empty string, but if this happens, I'd expect that either all variables are null (causing the `f:for` loop to not execute anything and thus throw no error and output no content) or that the other variable, `{panel.panel.active}` is also not assigned.

If the `{panels}` variable contains a proper array but the `{panel.panel.*}` variables are empty then I don't have any ideas as to why this might happen. Technically, it shouldn't be possible for such an element to assign different variables depending on context. I'm unaware of any TYPO3 core code that would treat variables differently if the element is in IRRE... and Flux definitely isn't sensitive to this type of context difference.

If you still have the problem and just worked around it, but you're still able to reproduce it by switching back, it might help if you can tell me a bit about how the IRRE elements get rendered? I'm assuming you use something like `v:content.render` or a custom piece of TypoScript which renders the objects by UID instead of rendering them by `colPos` value - if you use `v:content.render` I certainly wouldn't expect any difference, but if you use a custom TypoScript it could be a misconfiguration or incomplete configuration - or at worst, a core bug which somehow changes a part of the context when inside IRRE and in turn assigns incorrect variables (I'm guessing here, but if the active content record isn't correctly passed to `ContentContentObject` when inside IRRE then that might explain the difference).

At any rate, if you still have the problem then some additional information would be nice, e.g. which TYPO3 version you use and how you render the IRRE elements. And of course, if this is no longer relevant I'd like to close the issue (and perhaps recommend creating a bug report on forge.typo3.org).

PS: IRRE setups with `tt_content` as target are notoriously error prone not just in terms of rendering but also in terms of handling cascading `DataHandler` operations, in particular if the parent element is itself a record from the `tt_content` table. Generally speaking I'd advise against any form of IRRE to `tt_content` so if you have any alternative means, I'd change the strategy to avoid this IRRE.

**Comment by JanStorm** [comment] 2021-06-11 10:42
We ran into the same issue. TYPO3 v10.4.17, Flux v9.5.0
When try adding IRRE  content elements to news object with extension tx_news v8.5.2

**Comment by NamelessCoder** [comment] 2022-10-24 12:56
Initially reported issue (content area not defined) should now be solved by https://github.com/FluidTYPO3/flux/commit/8c27664d80528ca7498e99f42f7b5cb0cccedb01

**Closed by NamelessCoder** 2022-10-24 12:56 UTC
