### ISSUE TITLE
Missing typecast in backend

### ISSUE THREAD

**Issue by grischpel** [FluidTYPO3/flux#2055] opened 2023-01-05 12:09 UTC
flux\Classes\Integration\Overrides\BackendLayoutView.php 
Line: 117
Before:
$parentRecordUid = ColumnNumberUtility::calculateParentUid($this->record['colPos']);
After: 
$parentRecordUid = ColumnNumberUtility::calculateParentUid((int)$this->record['colPos']);

Sorry to open a new Issue, but i cant create a new Pull request

**Comment by lucmuller** [comment] 2023-01-05 13:53
Should be fixed by #2046

**Comment by lucmuller** [comment] 2023-01-05 13:55
Duplicate of #2045

**Comment by NamelessCoder** [comment] 2023-02-17 14:10
Solved by https://github.com/FluidTYPO3/flux/commit/3c944b576e01745d0c77f49e977df539597b7b81#diff-89545df00ad17f687303f6717cebcce3ceac29681e98d0cbed63fa9c21fdb0f1

**Closed by NamelessCoder** 2023-02-17 14:10 UTC
