### ISSUE TITLE
No TypoScript Configuration when insertig a new CE between CEs

### ISSUE THREAD

**Issue by fkalka** [FluidTYPO3/flux#1435] opened 2017-07-14 14:27 UTC
Hi,
i have the strange behavior, that when i insert a new CE between other CEs, i get an invalid template exception.
When i add content on top or bottom of the page everything is fine.
The problem is that when i call the following code in the getForm-Method of my Provider

`
$configurationManager = $objectManager->get('TYPO3\\CMS\\Extbase\\Configuration\\ConfigurationManagerInterface');
`
`
$ts = $configurationManager->getConfiguration(\TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface::CONFIGURATION_TYPE_FULL_TYPOSCRIPT);
`

does not return all the TS. It seems to me, that only static TS added for example with \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTypoScriptSetup is returned, everything from the template is missing.
When i add a CE on top/bottom of the page i get all the TS.

**Comment by fkalka** [comment] 2017-07-14 14:35
Forgot to mention:
Flux latest Repo-Version and TYPO3 8.7.3

**Comment by NamelessCoder** [comment] 2017-07-18 11:11
You need at least one `sys_template` record with `is_root=1` or the TYPO3 backend will be unable to resolve any TS in the backend. Without this, things like custom template paths cannot be respected.

The other possibility is that you've got some syntax error in the TS that prevents your specific TS from being parsed (parsing stops at syntax error but continues in next file).

My recommendation is to make your template paths setup as vanilla as possible so you can rely on the resolving by file name convention etc. and not need TS at all.

**Comment by fkalka** [comment] 2017-07-18 11:33
Thanks for your response. I have a root template set up.
I did debug the problem a bit, and in short (i will post some more details on this problem as soon as i have the time), that in the state when a Form is show (via CE edit-button or after CE wizard) the ID of the current page is lost (id parameter, used by ConfigManager to get the current page to lookup ts for). When flux is disabled, nothing makes a call to BackendConfigurationManager. With flux enabled, it is called.
I will attach some example to reproduce my problem shortly.
But i am quite sure, that the problem is on my site, because i was able to reproduce it on a fresh installation.
Also i don't think anymore it is flux related. If so, i will report a Bug on official TYPO3 Tracker.

**Comment by fkalka** [comment] 2017-07-18 12:11
Here is an example to show my problem:

place this code in FluidTYPO3\Flux\Configuration\BackendConfigurationManager->getCurrentPageId:
`\TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump($this->getPrioritizedPageUids());`

Now you see in the list module an array wich should hold the correct id (last value), then when you add a CE, in the wizard you still have the correct page uid. But one click later when the form is shown, the page id is gone. Flux's BackendConfigManager will return the uid of the previous content element, and if there is no page which happens to have the same uid, my code will fail.

I don't think anymore this is flux related, because it seems to be same behavior without flux. I will provide a testcase w/o flux soon.

**Comment by derhansen** [comment] 2017-07-20 05:53
I have a similar problem with TypoScript configuration, when `ext:flux` is installed.

In an Extbase extension, I retrieve the TypoScript configuration in a validator-class like shown below:

```
        $settings = $this->configurationManager->getConfiguration(
            ConfigurationManagerInterface::CONFIGURATION_TYPE_SETTINGS,
            'SfEventMgt',
            'Pievent'
        );
```

Without `ext:flux` installed, the TypoScript configuration is returned as expected and it includes all steps of TypoScript merging (e.g. config from Plugin and FlexForm).

With `ext:flux` installed, TypoScript is not merged, since the configurationManager instance is missing `extensionName`, `pluginName` and `contentObject`

Just ping me if you need additional information.

**Comment by timbadev** [comment] 2017-09-14 09:11
@fkalka have you been able to resolve this problem?

We have the exact same issue with:
* TYPO3 8.7.6
* VHS 4.3.1 / 4.2.0 (both tested)
* fluidcontent 5.2.0
* flux 8.2.1

It's weird that it works properly when inserting new elements at the top or bottom of a column, but fails when inserting between other elements

**Comment by moger-xx** [comment] 2017-10-12 11:28
I can confirm the issue with:
- TYPO3 8.7.8
- femanager 3.1.2 (dev-develop also tested)
- flux 8.2.1 (dev-master / dev-development also tested)
(no fluidcontent involved)

The problem is that no settings are returned in Femanager's AbstractValidator when using 
`        $config = $this->configurationManager->getConfiguration(
            ConfigurationManagerInterface::CONFIGURATION_TYPE_SETTINGS
        );`

**Comment by NamelessCoder** [comment] 2017-10-29 15:43
Flux no longer overrides the ConfigurationManager - see https://github.com/FluidTYPO3/flux/commit/4e147ef5b1ec6e14730cea75067a09461a110102. If the problem persists after the next release of Flux then please report this problem to the TYPO3 core bug tracker.

**Closed by NamelessCoder** 2017-10-29 15:43 UTC
