### ISSUE TITLE
BUG: flux interferes with TYPO3 caching

### ISSUE THREAD

**Issue by svewap** [FluidTYPO3/flux#2133] opened 2023-09-11 00:51 UTC
I have the suspicion that flux influences the cache of TYPO3. This causes INT objects to no longer work correctly. Felogin and form are examples.
Important: Do not force to use "no cache" in browser by developer bar.

**To Reproduce**
1. Insert a flux content element on a page.
2. Insert a felogin box on the page
3. Activate in plugin settings "Display Password Recovery Link [settings.showForgotPassword]" 
4. call the frontend. The recovery link should be visible
5. reload the page, the link disappears
6. Deactivate the flux content element, clear complete T3 cache and reload the frontend multiple times.
7. The link should always be visible

Can someone confirm this problem?

**Comment by NamelessCoder** [comment] 2023-09-11 10:50
Duplicate of https://github.com/FluidTYPO3/flux/issues/2126, fixed in Flux 10.0.4 by https://github.com/FluidTYPO3/flux/commit/d26fd1c91024150d4ec07fd71015c571e5f8be01. Associated with explicit ConfigurationManager vs. ConfigurationManagerInterface usagee in EXT:felogin - not associated with cache.

**Closed by NamelessCoder** 2023-09-11 10:50 UTC

**Comment by NamelessCoder** [comment] 2023-09-11 15:10
Please verify with the commit I pushed just now.
