### ISSUE TITLE
flux:field.select renderMode="checkbox" problems

### ISSUE THREAD

**Issue by alobeejay** [FluidTYPO3/flux#1142] opened 2016-05-18 08:25 UTC
The problem occurs only in the new version 7.4.0.
In the Typo3 Backend when editing an element under "Appearance->Container" the CSS class names are shown as a select dropdown instead of the checkboxes.

**Comment by julianstefanov** [comment] 2016-06-29 13:53
I got the same problem after update to typo3 7.6.9

**Comment by docDevel** [comment] 2016-07-05 19:05
I just got the same issue in 7.6.9 / flux 7.4.0 /fluid_contentcore 1.4.0
The Problem is a not correctly used argument, i think.

For e.g. in typo3conf/ext/fluidcontent_core/Resources/Private/Partials/Properties/Container.html
in line 22 is the argument **renderMode**="checkbox"

typo3conf/ext/flux/Classes/ViewHelpers/Field/SelectViewHelper.php   is using a parameter/argument named "renderType"

change the call to **renderType**="selectCheckBox" and it will work again.

this works for other content-elements as well...Partials/Properties/Images.html , Partials/Properties/Header.html etc.

It's just a temporary solution , so you can work on :D

**Comment by julianstefanov** [comment] 2016-07-05 19:09
Thank you very much docDevel!

**Comment by NamelessCoder** [comment] 2017-04-23 18:12
Thanks for the investigation and solution guys! However, I'm sorry to say we won't be fixing this one as there are no further planned updates for `fluidcontent_core` except for the inevitable deprecation it faces (which won't happen of course until there is a reasonable alternative to use Flux with native core types). So I'd fix this in your local templates for now and prepare at some point to switch to `fluid_styled_content` which we're working on integrating with Flux.

**Closed by NamelessCoder** 2017-04-23 18:12 UTC

**Comment by rickymathew** [comment] 2018-02-06 08:04
please do update the documentation here https://fluidtypo3.org/viewhelpers/flux/master/Field/SelectViewHelper.html  with the stuffs like alternative methods for 'rendermode'(renderType="selectCheckBox") as it consumes a lot of time to sortout and fix the deprecations.
