### ISSUE TITLE
Pasting container + child element does lead to lost parent/child structure

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/flux#1109] opened 2016-03-31 10:03 UTC
I'm testing at the moment with 7.6.4 LTS + flux developement + fluidpages 3.4.0 + fluidcontent 4.4.0 and I'm getting the following error. 

I got a structure with one container element which contains a child element. I am copying the container element and paste it in the root of a "normal" typo3 column (not a nested one). The result is that the the child element is no longer inside the container element but on the same level. When trying the same with multiple levels of nesting I'm getting every element on the same level as the container after pasting as well.

Looking at the `tt_content` table I can confirm the error since all the child elements lost their `colPos = 18181` once again. `tx_flux_column`, `tx_flux_parent` columns are correctly set. 

This makes copy/paste pretty useless and it did work with 6.2 LTS. Can someone confirm this bug?

**Comment by NamelessCoder** [comment] 2016-04-11 00:08
Possibly / very likely duplicate of any number of currently open issues describing this same symptom in various ways. Will try to merge those issues somehow.

**Closed by NamelessCoder** 2016-04-11 00:08 UTC
