### ISSUE TITLE
Multiple template collections not possible.

### ISSUE THREAD

**Issue by CodingForFunAndProfit** [FluidTYPO3/flux#911] opened 2015-09-06 13:49 UTC
I was trying the given solution in http://stackoverflow.com/a/27657857/3969007 simply to have different Layout/Template/Partial Paths on a subpage and/or additional rootpage.
I'm using:
typo3 6.2.14
flux 7.2.1
fluidpages 3.3.1
I tried to get to the bottom of this problem, but it seems that it fails on multiple places.
In FluxService.php in getAllTypoScript it will not get the correct current typoscript. By commenting out the following it reads the correct typoscript:
```
//if (0 === count(self::$typoScript)) {
	self::$typoScript = (array) $this->configurationManager->getConfiguration(ConfigurationManagerInterface::CONFIGURATION_TYPE_FULL_TYPOSCRIPT);
	self::$typoScript = GeneralUtility::removeDotsFromTS(self::$typoScript);
//}
```
In FluxService.php in getViewConfigurationForExtensionName the default hardcoded configuration should be merged with the typoscript-configuration which fails because of the incompatibility of the arrays.
```
Array
(
    [templateRootPaths] => EXT:sitetemplate/Resources/Private/Extensions/direct_mail/Templates/
    [partialRootPaths] => EXT:sitetemplate/Resources/Private/Extensions/direct_mail/Partials/
    [layoutRootPaths] => EXT:sitetemplate/Resources/Private/Extensions/direct_mail/Layouts/
)
```
and the default hardcoded array
```
Array
(
    [templateRootPaths] => Array
        (
            [10] => EXT:sitetemplate/Resources/Private/Templates/
        )

    [partialRootPaths] => Array
        (
            [10] => EXT:sitetemplate/Resources/Private/Partials/
        )

    [layoutRootPaths] => Array
        (
            [10] => EXT:sitetemplate/Resources/Private/Layouts/
        )
)
```

**Comment by NamelessCoder** [comment] 2015-09-07 10:19
I'm not 100% sure about the removal of the internal caching of loaded TypoScript - unless your code is actually running in multiple page contexts during the same query (which is definitely an edge case) you should always receive the same TypoScript on the same page UID in the backend. And the resolving should absolutely respect every TypoScript template you have in your root line. I have to assume this is caused either by an edge case or by the TypoScript itself being somehow invalid or returned incorrectly from Extbase's configuration manager.

Regarding getViewConfigurationForExtensionName: cannot confirm. You can see the function here: https://github.com/FluidTYPO3/flux/blob/development/Classes/Service/FluxService.php#L287 - and it should be fairly quick to see that it doesn't create the first array you provide. If your TypoScript actually contains this type of array (e.g. `plugin.tx_yourext.view.templateRootPaths = EXT:..../Templates/` - note the missing numeric index) then that's the cause of your incorrect paths. Adding the numeric index (and setting if higher than `10` (if you use the TER version of Flux - the patch that sets `0` as default is not in there yet so the default is still `10` in TER) should fix this.

I'm taking the liberty of assuming that this solves the problem. If it does, don't forget to put a little note on StackOverflow if an example there is bad or just to prevent others hitting the same blocker :)

**Closed by NamelessCoder** 2015-09-07 10:19 UTC

**Comment by CodingForFunAndProfit** [comment] 2015-09-07 10:46
Ok, I see that the patched Version and a correct TypoScript should solve the problem with the Arraymerging. The removal of the typoscript caching was just for testing and not a proposed fix. I wanted to show things I found. The problem seems to be that the cached typoscript is not the typoscript of the current page uid. This Line https://github.com/FluidTYPO3/flux/blob/development/Classes/Service/FluxService.php#L307 always returns the the wrong paths.

**Comment by NamelessCoder** [comment] 2015-09-10 14:23
Could you dig a bit deeper into this in the BackendConfigurationManager included with Flux, to learn the reason why your TS isn't being resolved correctly? Also, if you use the TER version then there was a related fix in Flux for resolving TS when editing pages - which seems relevant here. So if you haven't yet, please try our `development` branch.
