### ISSUE TITLE
Default sheet title can not be translated

### ISSUE THREAD

**Issue by zauni** [FluidTYPO3/flux#1082] opened 2016-02-19 14:21 UTC
Hi,
hopefully someone can help me with this. I have a default sheet coming up in a flux:form and I'm unable to translate the title.

This is my code:

```
<flux:form id="keyvisual" options="{group: 'components'}">
    <flux:field.input name="alt" label="LLL:keyvisual.alt" required="TRUE" />

    <flux:form.sheet name="config.sheets.options" label="LLL:config.sheets.options">
        <flux:field.input name="bar" label="LLL:config.bar" />
    </flux:form.sheet>
</flux:form>
```

And this is the outcome:

![screen](https://cloud.githubusercontent.com/assets/663845/13177488/b0ed77da-d719-11e5-9890-24e8131e269a.png)

It's wrapping the field.input inside a sheet, but it has a default title. To translate it, I already tried:

* Updating translation files of flux extension
* Using Page TSConfig: TCEForm.tt_content.pi_flexform.extension_pi1.[options,default,sDEF].sheetTitle=MyTitle
* Adding translation keys inside of the locallang.xlf named flux.fluxFormId.sheets.[options,default,sDEF]

Unfortunately nothing is working. Also something strange: Inside the flux extensions locallang.xlf is a translation key named `tt_content.tx_flux_options` and if I var_dump the $label inside `FluidTypo3\Flux\Form\AbstractFormComponent::resolveLocalLanguageValueOfLabel` it's trying to get the translation of `LLL:EXT:flux//Resources/Private/Language/locallang.xlf:tt_content.tx_flux_options`. So it looks like flux tries to load it's own translation for the default sheet and it is also failing.

Is someone having the same problem? Thanks for any help :)

**Comment by NamelessCoder** [comment] 2016-02-25 13:24
Duplicate of https://github.com/FluidTYPO3/flux/issues/1057 - but thanks for adding screenshot and additional information, we'll be able to locate that from the original issue too :)

**Closed by NamelessCoder** 2016-02-25 13:24 UTC

**Comment by zauni** [comment] 2016-02-25 14:02
Thanks for your reply!
Okay, now if I remove the / inside the `EXT:flux/Classes/Form.php` it is loading the right translation from the flux locallang file. 
But it is also not possible to use my own locallang file to translate the default sheet because it's hardcoded into the code. Would it be possible to extend the Form class to overwrite the `initalizeObject` method? How can I say flux to use my Form class instead of it's own Form class?

If this is not possible I can also include my own default sheet for every content-element, but would have been nice :)

**Comment by zauni** [comment] 2016-03-03 13:35
Okay, I got it working by using the XCLASS mechanism and by extending the Form's `initializeObject` method.
