### ISSUE TITLE
how to inherit/access page-settings between parent and sub-template?

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#896] opened 2015-08-20 13:50 UTC
I would expect any way to access and/or inherit settings of a rootpage template from within a sub-template.

Currently I don't see any way. So f.e. if I use a form file-field "logo" I must re-declare it for every template used!

There's a hack that makes it possible to retrieve settings from flexform (f.e. tx_fed_page_flexform) of another page.

But this still only is a bad workaround in my eyes and does no settings-merging and it is still limited to a FIXED uid.

This is very unflexible f.e. if you want to be able to override settings for sub-pages and if the next parent for 'tx_fed_page_flexform' is not the real rootpage (uid:1) but a child-page of it and the parent of our current sub-page (root - > sub to override some field -> current child page)

```
{flux:form.data(uid: 1, table: 'pages', field: 'tx_fed_page_flexform')-> v:variable.set(name: 'parentSettings')}
```

I think the best way would be to extend form.data with something like a slide-attribute (just like done for content-rendering in VHS).

**Comment by typoworx-de** [comment] 2015-08-20 14:49
I reported this issue to EXT:fluidpages as well as it seems to be issued by their code if I am not lying wrong..

https://github.com/FluidTYPO3/fluidpages/issues/273

**Comment by NamelessCoder** [comment] 2015-08-22 14:31
Duplicate of https://github.com/FluidTYPO3/fluidpages/issues/273 - inheritance is a fluidpages-specific behavior that resides in the Providers it contains.

**Closed by NamelessCoder** 2015-08-22 14:31 UTC
