### ISSUE TITLE
\FluidTYPO3\Flux\View\PreviewView::drawGridColumn leads to execption in BE if contentElementCache has not been build

### ISSUE THREAD

**Issue by mrk131324** [FluidTYPO3/flux#1112] opened 2016-04-04 15:35 UTC
The command 
```php
$localizeButton = $dblist->newLanguageButton(
	$dblist->getNonTranslatedTTcontentUids($childrenUids, $dblist->id, $langPointer),
	$langPointer
);
```

in `\FluidTYPO3\Flux\View\PreviewView:293` can create an exception in the page module if called before \TYPO3\CMS\Backend\View\PageLayoutView::$contentElementCache has been build.

In our case that happens for the columns of a page template with multiple flux grid columns if at least one content element can be translated (and thus the button is rendered).

**Comment by NamelessCoder** [comment] 2016-04-04 16:39
Duplicate of https://github.com/FluidTYPO3/flux/issues/1086 - summary: core regression, fix awaited in TYPO3 7.6.5.

**Closed by NamelessCoder** 2016-04-04 16:39 UTC
