### ISSUE TITLE
csv for items on flux:field.select not working as expected

### ISSUE THREAD

**Issue by andyhausmann** [FluidTYPO3/flux#1548] opened 2018-05-02 13:05 UTC
Hey guys,

we've recently updated a project to the latest 7 LTS version + php@7.1 + flux@8.2.1.
After that, we had to implement the latest version of flux.

After that, the following changed:

<flux:field.select name="settings.grid2.split" items="6-6,8-4,4-8,9-3,3-9,..." default="6-6" requestUpdate="1" />

changed from a list of 6-6,8-4, etc. to a confusing list of 6,5,4,3,2,1,\,.

Why did that happen and how to fix that? It would be great of key and value still could be the same.

**Comment by NamelessCoder** [comment] 2018-07-08 19:09
Hi @andyhausmann - if the code example you gave is actually exactly what's in your template, then I think the cause for your problem is the new "range" feature you can use in the value of "items":

`<flux:field.select items="1..10" />`

Makes values from 1 to 10. It triggers if your items property is a string and contains `..`.

You might be able to avoid it by using `&ellipsis;` as replacement for your `...` string. If that does not work, we would perhaps need a fix in the `Select` component to make detection of a range include more checks.

**Comment by NamelessCoder** [comment] 2019-03-03 03:36
Closing as "assuming fixed" ;)

**Closed by NamelessCoder** 2019-03-03 03:36 UTC
