### ISSUE TITLE
flux:form.data returns array (empty)

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/flux#1521] opened 2018-02-20 08:57 UTC
**I use:**
TYPO3 8.7.10
FLUX 8.2.1
```
<flux:form.data table="tt_content" field="pi_flexform" uid="1" as="flexformData">
               {flexformData -> f:debug()}
</flux:form.data>
```
**In database I see it:**
```
pi_flexform => '<?xml version="1.0" encoding="utf-8" standalone="yes" ?> <T3FlexForms> <
      data> <sheet index="sDEF"> <language index="lDEF"> 
       <field index="switchableControllerActions">....
```
**I'm getting array (empty)**

I looked for #1216 #1463 #1215 but that did not help me

**Comment by glucka** [comment] 2018-03-05 10:01
i can confirm this issue

**Comment by NamelessCoder** [comment] 2020-06-28 10:33
Unable to confirm - when testing, this works with any combination of record/field/uid and with/without use of the `as` argument. Since no other users have reported this kind of problem I have to assume it is caused by, for example, malformed XML content in the database field which causes `\TYPO3\CMS\Core\Service\FlexFormService::convertFlexFormContentToArray` to convert the array incorrectly, or is caused by an overridden `\FluidTYPO3\Flux\Provider\AbstractProvider::getFlexFormValues` which is programmed to return an empty array.

Closing the issue since it is more than two years old.

**Closed by NamelessCoder** 2020-06-28 10:33 UTC

**Comment by typo3ua** [comment] 2020-06-29 08:41
Thanks for reply, maybe you are right, i already do not know what was next I know that i do not found a solve and i just stopped use flux.
