### ISSUE TITLE
Referencing content items with child items bug

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/flux#818] opened 2015-05-06 11:25 UTC
Here is my setup: flux@7.2.0 (or developement), fluidpages@3.2.2, fluidcontent@4.2.1, vhs@2.3.2, typo3@6.2.12.

If you reference (using the reference icon) a content item that contains child items not only the reference item gets created but also a copy of all the child items of the referenced wrapper.

Here are two screenshots documenting the issue.

_Page view not showing the child items (correct)_

![9290166c-dde1-11e4-89cd-2ebb672e824c](https://cloud.githubusercontent.com/assets/157281/7492261/479abaa0-f3f2-11e4-9cb5-b792abd60c8c.png)

_List view shows the copied dummy items (bug)_
![928ea1d8-dde1-11e4-96d1-980befc06cbd](https://cloud.githubusercontent.com/assets/157281/7492267/58b84a82-f3f2-11e4-9d6b-47f137bb0943.png)

**Comment by xf-** [comment] 2015-07-26 00:49
confirmed

**Comment by NamelessCoder** [comment] 2015-09-11 14:58
I think we somehow need to halt the DataHandler's further processing so it doesn't try to "copy" any other record than the one that gets referenced.

Alternatively we may want to just manually copy the source record in SQL and adjust parameters, then stop DataHandler from doing anything to it. We are after all not creating a copy as such - we're only using "copy" as command because that copies things like access controls and visibility (giving the reference an additional set of controls that are applied before the target record gets rendered). This may just as well be a 1:1 SQL copy; we just need to adjust the relationship fields after.

**Comment by NamelessCoder** [comment] 2015-09-28 17:46
Just an update: the *symptom* of this problem is now gone (the redundant child records are not visible) but the problem itself remains. Child records are still being duplicated as described but must be viewed directly in DB when debugging.

**Comment by chuenniger** [comment] 2016-06-14 13:07
Hi

Is planned to release a fix to the TYPO3 6 LTS version? (7.2.4?)

**Comment by NamelessCoder** [comment] 2016-06-14 14:25
@chuenniger No, no such plans. Once the bug gets fixed anyone is welcome to cherry pick it and open a pull request targeting the 'legacy' branch - but we in the team no longer maintain or release versions compatible with 6.2. We'll merge the pull request if it is good, but that's about it :)

**Comment by NamelessCoder** [comment] 2018-07-08 18:53
Solved as part of https://github.com/FluidTYPO3/flux/pull/1563, will be included in release 9.0. Please see the PR for more details, among other things about how to use the migration script.

* "Paste as reference" is removed. There is an alternative procedure described on https://github.com/FluidTYPO3/flux/issues/1305#issuecomment-328512665.
* Nearly all of the overrides that caused unexpected operations on child content have been removed and will no longer be triggered.

**Closed by NamelessCoder** 2018-07-08 18:53 UTC
