### ISSUE TITLE
Section id not written when creating a fluidcontent element

### ISSUE THREAD

**Issue by Kitzberger** [FluidTYPO3/flux#1179] opened 2016-09-07 17:11 UTC
Not quite sure if it's a fluidcontent or a flux bug, but I'm kinda sure that it's not related to the whole nested section story.

When saving a freshly created fluidcontent element that provides a section the section xml lacks an id:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<T3FlexForms>
    <data>
        <sheet index="options">
            <language index="lDEF">
                <field index="main.title">
                    <value index="vDEF"/>
                </field>
                <field index="main.subtitle">
                    <value index="vDEF"/>
                </field>
                <field index="tabs">
                    <el index="el">
                        <section index="1">
                            <itemType index="tab">
                                <el>
                                    <field index="title">
                                        <value index="vDEF">Test2</value>
                                    </field>
                            </itemType>
                            <itemType index="_TOGGLE">0</itemType>
                        </section>
                    </el>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms>
```

The id is only being written when editing the section and saving the fluidcontent element for the second time. It then adds this line:

```
<field index="id"><value index="vDEF">f0d255c0317c415313a9d58ea2bbc1210da1c7a5</value></field></el>
```

Maybe you can point me in the right direction to debug this any further. Thanks ;-)

**Comment by NamelessCoder** [comment] 2016-09-07 20:46
This one is - unfortunately - outside our control. The only way to work around it is to add a condition or displayCond for the section so it does not display unless the record has been saved once. It stems from TYPO3 *no longer passing any record when fetching a DS for a `flex` type field when creating new elements*. It is technically (very technically) a regression but fixing it is a difficult one to fix - so we understand why it is not prioritised (honestly, there are other issues of far greater importance in FormEngine).

This specifically affects Flux because Flux *uses dynamic resolving of the DS according to values saved in the record*. So the result of this inability of TYPO3 to pass an (incomplete, unsaved) record is that Flux cannot deliver a DS. We get around this currently with a patch that session-caches DS based on selected fluidcontent type - but this is only a half measure. It allows the DS to function if at any point in the session you've edited an existing element of the same type. It is **very much a compromise**.

The current compromise was reached in cooperation with Christian Kuhn who architected the FormEngine changes. It is unlikely it will be fully fixed on 7.6 LTS and the fate of a potential patch for TYPO3v8 series is unknown. The sad conclusion is that this is *very* low priority because all non-dynamic ways of delivering a DS are not affected. And among all community extensions, Flux is probably the most affected. We are simply not expecting a fix for this any time soon.

The best we can do is encourage devs with the necessary skills to try and fix this regression in TYPO3. Or ask agencies if any are affected and wish to sponsor the creation of a fix - in which case I hate to say it because he's probably a busy man: but Christian Kuhn would be *the* right person to sponsor for making such a patch. I don't mind coordinating but it would definitely be a big help to us (the team) if "someone" would take it upon themselves to push this one up the hill ;)

Would you be interested in doing that?

**Comment by NamelessCoder** [comment] 2016-11-12 14:48
We will be implementing `displayCond` in fluidcontent and fluidpages to avoid displaying the options field if the record has not yet been saved. We do this to accommodate recent changes in FormEngine regarding the DS retrieval: https://github.com/FluidTYPO3/flux/pull/1203.

With this we consider the issue solved (or, as much solved/avoided as is possible to do given changes in the TYPO3 core).

**Closed by NamelessCoder** 2016-11-12 14:48 UTC

**Comment by Kitzberger** [comment] 2016-11-13 09:12
Thanks for the feedback, Claus!

Will this be already a feature in Flux 7.5? And probably only be available for TYPO3 >= 8 LTS, right?

**Comment by NamelessCoder** [comment] 2016-11-13 11:38
Flux 7.5 will include it - 7.6 LTS is also affected.
