### ISSUE TITLE
Exception in backend view when CType="list" and list_type=""

### ISSUE THREAD

**Issue by myhandicap** [FluidTYPO3/flux#830] opened 2015-05-13 13:01 UTC
When I select "Insert Plugin" for an existing tt_content object, I get the following exception
 ```#1257246929: "" is not a valid template resource URI. ```

After some debugging I found out that this exception happens when CType="list" and list_type="". This problem only occurs in combination with other plugins (a fresh installation with only flux has no problem with this).
The debug trace lead to ContentIconHookSubscriber but I did not have success in finding the causing problem.

A workaround for me was to patch the trigger function of AbstractProvider to have $matchesPluginType===FALSE when list_type is empty.

**Comment by xf-** [comment] 2015-07-26 00:44
Can you provide more information for our test.
Version and extensions
Core, flux, fluidcontent_core....

**Comment by myhandicap** [comment] 2015-07-26 05:20
We initially had the problem with an 6.2.X core but it is still the same on Core 6.2.14
We use
Flux 7.2.0 and
fluidcontent 4.2.1

**Comment by jmverges** [comment] 2015-07-27 12:54
HI @myhandicap,

I'm not able to reproduce it with last 6.2 LTS or 7 master. 

My steps:
In a page I create a content element Text. 
I save it and I am returned to Preview view.
I edit the text element and I select Insert Plugin.
I save it and I am returned to Preview view.
I'm able to see the label: "No plugin selected"


![v7noplugin](https://cloud.githubusercontent.com/assets/2902073/8906470/54c501f0-346f-11e5-9917-924d6ba09695.png)

![v6noplugin](https://cloud.githubusercontent.com/assets/2902073/8906473/56e6290a-346f-11e5-91f0-dde181e3e799.png)


Let us know if your steps are different.

**Comment by NamelessCoder** [comment] 2015-07-27 15:30
Fixed a few weeks ago - but I think the fix is only in the `development` branch at this point. It will be released to TER soon, though!

**Closed by NamelessCoder** 2015-07-27 15:30 UTC
