### ISSUE TITLE
flux:form.object into flux:form.object don't work

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/flux#845] opened 2015-06-12 21:01 UTC
~~~
<flux:form.sheet name="11" label="11">
	<flux:form.section name="1rs" label="1rs">
		<flux:form.object name="1r" label="1r">
			<flux:form.section name="1ts" label="1ts">
				<flux:form.object name="1t" label="1t">
				
				</flux:form.object>
			</flux:form.section>
		</flux:form.object>
	</flux:form.section>
</flux:form.sheet>
~~~

This code don't work with FLUX master

With the old version FLUX running.

**Comment by NamelessCoder** [comment] 2015-06-12 23:05
Duplicate of https://github.com/FluidTYPO3/flux/issues/835, fixed since. Make sure your innermost object contains at least one field.

**Closed by NamelessCoder** 2015-06-12 23:05 UTC
