### ISSUE TITLE
[BUG][TYPO3-7.6] Wrong child-record language after using "Translate > copy"

### ISSUE THREAD

**Issue by BenjaminBeck** [FluidTYPO3/flux#1099] opened 2016-03-13 11:51 UTC
If i copy (with translation wizzard) a container with one child element from default language (ID:0) to a alternative language (ID:7) the new created child-record still has sys_language_uid=0.

If "Translate > localize" in the wizzard is used, the child-element gets the correct language (ID:7).

Setup:

| Extension | Version |
| --- | --- |
| flux | development branch (2016-03-13; aff30de) |
| fluidpages | 3.5.0 (5cbb73f) |
| TYPO3 | 7.6.4 (bd0c7f6) |

![screenshot 2016-03-13 12 21 55](https://cloud.githubusercontent.com/assets/1185872/13728439/3d3428cc-e919-11e5-83ac-69ae341e5a0e.png)

**Comment by BenjaminBeck** [comment] 2016-03-13 19:38
This is a core bug.
I did not find a direct issue for this but it may be related to: https://forge.typo3.org/issues/73604
Gridelements has the same problem: https://forge.typo3.org/issues/72674#change-299523

I would suggest to leave this issue open until it´s fixed in the core..

**Comment by cedricziel** [comment] 2016-03-13 19:53
It could be that it just uses a bunch of different hooks than the reference mechanism.

**Comment by BenjaminBeck** [comment] 2016-03-14 14:42
@cedricziel You are talking about the sys_file_reference records (e.g. used in image ce)?
I checked those: They have the same problem! But you dont see it until you set the language-field to visible ..

**Comment by BenjaminBeck** [comment] 2016-03-16 09:38
I made a bugfix-extension for the time being:
https://github.com/BenjaminBeck/bdm_bugfix_translatecopy
First tests look good.. but if you use it, it´s at your own risk..

I would like to hear if anybody else has the same problem, or are you on an older 7.6.x version where this bug does not exist?
Does this bugfix-extension help you? (I would love to see some +1 reacts (: )

**Comment by DenisMir** [comment] 2016-03-31 09:26
@BenjaminBeck I can confirm the error and have tried your bugfix extension with the latest 
7.6.4 LTS release and it does work perfectly as far as I can tell. Reading through the Gridelements issue I'm afraid that the core bug is far away from being fixed in the upcoming months.

**Comment by SLoeffler** [comment] 2016-11-15 07:48
Are there any news regarding this issue?

**Comment by NamelessCoder** [comment] 2016-11-15 09:32
If nothing new is recorded in this issue, nothing new has happened since last time. Check the issue tracker for any related issues that may have progressed further, check the situation in the TYPO3 core if it is fixed, try to implement the fix extension from @BenjaminBeck, propose a PR or add your debugging information if you wish this to move quicker.

**Comment by BenjaminBeck** [comment] 2016-11-24 13:53
Its moving: https://forge.typo3.org/issues/78059

TYPO3 8.x
https://github.com/TYPO3/TYPO3.CMS/commit/57d452db9bb933e786d03a3acd7df6489adc6542

TYPO3 7.6.x
https://github.com/TYPO3/TYPO3.CMS/commit/4d4a519b0210625bca81292123f79a723906e1d3

So this fix should be already in 7.6.12
But i haven´t had the time to test and check it ..

**Comment by NamelessCoder** [comment] 2016-11-24 16:40
Thanks for updating, Benjamin! If someone tests this and it works please throw a "confirmed!" our way ;)

**Comment by simare** [comment] 2017-01-04 09:12
I tested it today, but it did not work.
Using:
TYPO3 7.6.14
Flux Development@69273f2
<img width="645" alt="bett bike typo3 cms 7 6 14" src="https://cloud.githubusercontent.com/assets/514514/21637224/445180c8-d266-11e6-8afa-7a7c6f2034f4.png">

**Comment by NamelessCoder** [comment] 2017-01-04 12:29
> I tested it today, but it did not work.

Please read above - this is a *core bug* and the issue Benjamin links to above is *still open*, so obviously this one is not fixed yet.

**Comment by mneuhaus** [comment] 2017-01-28 10:39
@NamelessCoder finally managed to locate a core bug causing this behavior 👍 
a core patch is coming up :)

**Comment by Tuurlijk** [comment] 2017-01-31 12:52
@mneuhaus Can you post the link to the patch / issue here?

**Comment by mneuhaus** [comment] 2017-01-31 13:05
after quite some more digging, etc. it turns out, there's a quit recent patch already in core + 7.6 and will be in the next 7.6 bugfix release:
https://forge.typo3.org/issues/75400

cheers

**Comment by NamelessCoder** [comment] 2018-07-08 18:42
Solved as part of https://github.com/FluidTYPO3/flux/pull/1563, will be included in release 9.0. Please see the PR for more details, among other things about how to use the migration script.

**Closed by NamelessCoder** 2018-07-08 18:42 UTC
