### ISSUE TITLE
Again: flux:form.data returns empty record from pi_flexform

### ISSUE THREAD

**Issue by EdRoxter** [FluidTYPO3/flux#1463] opened 2017-09-14 14:45 UTC
After I had upgraded flux to the latest compatible version with my Typo3 instance (that's Flux 8.2.1 on Typo3 7.6.22 with a multilang setup by now), I'm having the same problem again like in #1216: When I try to get the pi_flexform of another tt_content record, the variable is just empty.

In my Flux template I have:
`<f:debug title="Fluxparent">{record.tx_flux_parent}</f:debug> <f:debug title="ForeignFlexform">{flux:form.data(table:'tt_content', field:'pi_flexform', uid:'{record.tx_flux_parent}')}</f:debug>`
The debug output shows like:
```
Fluxparent
'5939' (4 chars)
ForeignFlexform
array(empty)
```

When, for a test, I try to get content_options instead of pi_flexform, it works flawlessly:
`<f:debug title="Fluxparent">{record.tx_flux_parent}</f:debug> <f:debug title="ForeignFlexform">{flux:form.data(table:'tt_content', field:'content_options', uid:'{record.tx_flux_parent}')}</f:debug>`
Result:
```
Fluxparent
'5939' (4 chars)
ForeignFlexform
array(1 item)
   settings => - array(2 items)
      header => + array(2 items)
      container => + array(2 items)
```

The raw flexform XML code in the database cells looks exactly the same to me, structurally:
pi_flexform:
```
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3FlexForms>
   <data>
       <sheet index="options">
           <language index="lDEF">
               <field index="settings.fullsize">
                   <value index="vDEF">fullsize</value>
               </field>
           </language>
       </sheet>
   </data>
</T3FlexForms>
```

content_options:
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<T3FlexForms>
   <data>
       <sheet index="header">
           <language index="lDEF">
               <field index="settings.header.type">
                   <value index="vDEF">2</value>
               </field>
               <field index="settings.header.className">
                   <value index="vDEF"/>
               </field>
           </language>
       </sheet>
       <sheet index="container">
           <language index="lDEF">
               <field index="settings.container.addAnchor">
                   <value index="vDEF">0</value>
               </field>
               <field index="settings.container.className">
                   <value index="vDEF"/>
               </field>
           </language>
       </sheet>
   </data>
</T3FlexForms>
```

Also, https://github.com/FluidTYPO3/flux/pull/1215/commits/31a6d770882f98a6366e71d4adc4b66e2b931fb9 seems to be merged into the upstream version for long time already (checked the PHP file in my typo3conf/ext/flux directory and the changes from the pull request are definitely reflected in it), so I guess this can't be the same issue again - but I'm having the same symptoms again.

Any help would be greatly appreciated! :)

**Comment by NamelessCoder** [comment] 2017-10-30 01:08
Phew, this is a tough one - the short version is I'm going to have to close this issue as "won't solve". First, the reasons:

* Flux will drop 7.6 support in the next release and no further 8.2.x updates will be made.
* On TYPO3 7.6 a *much* older framework is used to resolve the data sources and settings, which among other things supports language-based reading of values.
* The patch that did affect this issue is already merged and as you found included in 8.2.1, but: the logic that reads the FlexForm data is very different - and several patches have been made to it since then (not just in Flux but in TYPO3 as well).
* There could be an excessive number of different reasons why `pi_flexform` might fail to produce values while `content_options` works - among other things, different Providers are returned for each. It appears that at least you are using `fluidcontent_core` which is no longer supported and this could also have an effect.
* I haven't been able to reproduce the problem on TYPO3 8.7 or dev-master (which both ignore language settings, that could be a hint) - that doesn't mean it doesn't exist there, just that it doesn't trigger under normal circumstances.

If you are able to reproduce this on 8.7 I will happily reconsider, but it would help a lot if you can debug the logic and maybe find the reason why no data is resolved on *your* setup.

The best place to do this is probably in the AbstractProvider class from PHP, in getFlexFormValues(). And it's worth checking in DataViewHelper if Provider classes get resolved - because if no Provider classes get resolved, the standard TYPO3 FlexForm processing will be used and if *that* fails you've eliminated Flux as the cause, and should open a bug report in the TYPO3 core bug tracker.

Hope this helps - and sorry for closing the issue without a solution, but hopefully the above situation explains why even if it were possible to fix this issue, no new releases will be made, and the next release will not support the TYPO3 version you use, so you would be no better off. Your very best option, also generally speaking, would be to upgrade TYPO3 to 8.7 LTS since that gives you access to bug fixes for both TYPO3 and Flux concerning FlexForms.

**Closed by NamelessCoder** 2017-10-30 01:08 UTC
