### ISSUE TITLE
Issue with copying localized grid elements

### ISSUE THREAD

**Issue by fnagel** [FluidTYPO3/flux#1683] opened 2019-03-21 09:39 UTC
I'm having issues when copying localized grid elements in TYPO3 8.7.24 with EXT:flux (1d4642384f3cda38f4a5e1ae5ab55dd4cabec073). I've tested this in a custom installation and a fresh introduction package instance.

## How to reproduce

Here's what I do:

* Create a new page
* Add a grid (see template below)
* Add content within the grid element
* Localize the grid and its content
* Copy that grid element
* Localized grid content is placed within the default language grid (see screenshot)

## Screenshots

![1](https://user-images.githubusercontent.com/116824/54743792-7d0aa180-4bc5-11e9-9bbe-75e2c88a6acd.PNG)
![2](https://user-images.githubusercontent.com/116824/54743794-7d0aa180-4bc5-11e9-9fc7-81aac51ccd18.PNG)
![3](https://user-images.githubusercontent.com/116824/54743795-7d0aa180-4bc5-11e9-941f-05844faaa491.PNG)
![4](https://user-images.githubusercontent.com/116824/54743796-7d0aa180-4bc5-11e9-872a-f372ec5f6a31.PNG)
![5](https://user-images.githubusercontent.com/116824/54743797-7d0aa180-4bc5-11e9-82f8-debd0bf2d361.PNG)
![6](https://user-images.githubusercontent.com/116824/54743798-7da33800-4bc5-11e9-86d5-d239244fccc9.PNG)

## Template (simplified)

	<f:section name="Configuration">
		<v:variable.set name="columnItems" value="{
			null: 'Default (equal width)',
			'12': 'Full width',
			'10': '5/6 width',
			'9': '3/4 width',
			'8': '2/3 width',
			'6': '1/2 width',
			'4': '1/3 width',
			'3': '1/4 width',
			'2': '1/6 width'
		}" />

		<flux:form id="row" label="Grid Row" description="Add content in columns.">
			<flux:form.option.group value="common" />
			<flux:form.option.icon>EXT:project/Resources/Public/Icons/grid.svg</flux:form.option.icon>

			<flux:form.section name="columns">
				<flux:form.object name="column" label="Column">
					<flux:field.select label="Large devices" name="class-large" items="{columnItems}" />
					<flux:field.select label="Medium devices" name="class-medium" items="{columnItems}" />
					<flux:field.select label="Small devices" name="class" items="{columnItems}" />
					<flux:field.checkbox name="center" label="Center column" />
				</flux:form.object>
			</flux:form.section>
			<flux:grid>
				<flux:grid.row>
					<v:condition.type.isArray value="{columns}">
						<f:for each="{columns}" as="sectionObject" iteration="iteration">
							<flux:grid.column name="column{iteration.cycle}" colPos="{iteration.cycle}" label="auto" />
						</f:for>
					</v:condition.type.isArray>
				</flux:grid.row>
			</flux:grid>
		</flux:form>
	</f:section>

**Comment by NamelessCoder** [comment] 2019-03-21 10:04
@glucka Apologies for the ping but could I have you take a look at this one? I'm guessing there's some place in the data handler hook that sets the "colPos" not only for copied but also original records...

**Comment by glucka** [comment] 2019-03-21 10:07
@NamelessCoder no problem, i try to reproduce in the afternoon

**Comment by glucka** [comment] 2019-03-21 13:02
The first problem what i have is at this commit ae671cc805f16bf43b90edd72cf367c875aef067
This commit break the translate process on TYPO3 v9. I keep researching.

**Comment by NamelessCoder** [comment] 2019-03-21 13:10
That commit shouldn't be related - the issue is reported on 8.7 and https://github.com/FluidTYPO3/flux/commit/90774c92df697b00a8f773e057020c3942f9c1df adds a guard clause to use the core's own code when translating on 8.7. But if translation is broken on v9 and that override is the cause, I hope you can fix that at the same time! :)

**Comment by glucka** [comment] 2019-03-21 13:26
After making a fix for this: ae671cc805f16bf43b90edd72cf367c875aef067, can i confirm this issue on v9 too. Make a PR now.

**Comment by glucka** [comment] 2019-03-21 13:59
@fnagel i tryed only on TYPO3 v9 but it schould work on v8 too. Please test

**Comment by fnagel** [comment] 2019-03-21 14:32
Test in TYPO3 8.7 without issues. Thanks for your help!

**Closed** 2019-03-21 17:49 UTC
