### ISSUE TITLE
Nesting sections in container elements sections is not allowed.

### ISSUE THREAD

**Issue by yooapps-bub** [FluidTYPO3/flux#1139] opened 2016-05-06 15:18 UTC
Hello everybody,

in TYPO3 7.6.4 I successfully used sections in sections. Now I have a new project with version 7.6.6 and I created an element with the configuration:
`<f:section name="Configuration">
	<flux:form id="resident">
		
		<flux:form.section name="resident">
			<flux:form.object name="person">
				<flux:field.input name="name" required="true" />
				<flux:field.input name="informations" />
				<flux:form.section name="portrait">
					<flux:form.object name="data">
						<flux:field.input name="title" />
						<flux:field.input name="text" />
					</flux:form.object>
				</flux:form.section>
				<flux:form.section name="faq">
					<flux:form.object name="data">
						<flux:field.input name="question" />
						<flux:field.text name="answer" rows="5" cols="30" enableRichText="TRUE" />
					</flux:form.object>
				</flux:form.section>
			</flux:form.object>
		</flux:form.section>
	</flux:form>
</f:section>`

If I select the content element TYPO3 display the error "Invalid flex form data structure on field name "pi_flexform" with element "portrait" in section container "person": Nesting sections in container elements sections is not allowed."

Is there a way to fix this problem?
Thanks for your help.

Greetings
Bjoern

**Comment by deerfish** [comment] 2016-05-06 15:18
Guten Tag
 
Vielen Dank für Ihre Nachricht.

Ich bin vom Donnerstag, 05. Mai 2016 bis und mit Freitag, 06. Mai 2016 wegen eines Feiertages nicht erreichbar, und gerne am Montag, 9. Mai wieder für Sie da.
 
Die Nachricht wird nicht weiter geleitet! In sehr dringenden Angelegenheiten bin ich auf dem Mobile zeitweise erreichbar. Falls nicht hinterlassen Sie bitte eine Nachricht, damit ich Sie zurückrufen kann. Vielen Dank!


Einen guten Tag wünscht

Damian Parpan



Damian Parpan
appline
Hirschengraben 52
6003 Luzern
Switzerland

T: +4141 266 0034
M: +4179 303 4878

Email: damian.parpan@appline.ch
www.appline.ch

**Comment by QID-Service** [comment] 2016-05-23 21:34
Hello,
I can confirm this problem. Worked with Typo3 7.6.2 and flux 7.3.0.
But with Typo3 7.6.4/7.6.5 and flux 7.4.0 I get the following error:

#1458745712: Invalid flex form data structure on field name "pi_flexform" with element "subelements" in section container "image": Nesting sections in container elements sections is not allowed. 

Is there a way to fix it?

Thanks
Jörg

**Comment by orangenpresse** [comment] 2016-05-24 09:41
It was broken by: https://git.typo3.org/Packages/TYPO3.CMS.git/commit/8ae9f625683c86e38a757f176f8e86eb7c11dde2

If you remove the check from TcaFlexProcess.php everything works fine.
I think this is not a flux bug.

**Comment by lolli42** [comment] 2016-05-24 10:33
Yes, you can remove the check manually.
Problem is that the data preparation is NOT done for nested sections at all, so anything more complex than a simple input field will fail or will lure into false positives. There is literally no checks whatsoever on the data. You will face missing options, wrong labels, not executed functions and data loss on safe in you remove the exception for pretty simple select or group elements already.
This is not acceptable from core point of view, thus the exception was introduced to simply declare that such scenarios are not supported at the moment.

**Comment by NamelessCoder** [comment] 2016-05-24 11:20
Thanks for the background @lolli42 - I happen to agree, not least since Flux receives a big chunk of bug reports about such inline stuff as we've already discussed and fixed together ;)

**Comment by orangenpresse** [comment] 2016-05-24 11:31
Thanks @lolli42 that information is very good. I agree with you now too.
Also with the grid system it should be possible to workaround every case.

**Comment by NamelessCoder** [comment] 2016-05-24 12:47
To add a bit of FluidTYPO3 background before I close this:

We've right from the start seen Flux as an abstraction of the core's API for FlexForms/TCA. If something is not supported there we are perfectly okay saying it's not supported in Flux either. So we appreciate exceptions rather than half solutions and welcome the same restrictions applied to other half supported structures.

As with anything there are exceptions. Right now, Flux applies a patch that allows using FAL as IRRE in FlexForms - without which there would be fatal errors. We applied this patch because FAL as IRRE is such a vital feature for custom content without TCA modifications.

Breaking or amending what the core supports in terms of TCA structure, on the other hand, cannot be considered a vital feature - so we will not be catching such exceptions and hacking structures to achieve an undesirable result.

Thanks to everyone involved with reporting/explaining!

Note to self: document what these new exceptions mean in a Flux context, on the exception link TYPO3 generates.

**Closed by NamelessCoder** 2016-05-24 12:47 UTC

**Comment by dneuge** [comment] 2016-06-15 10:56
I just noticed this yesterday. I've taken the time to start documentation of exception [1458745712](https://wiki.typo3.org/Exception/CMS/1458745712) and add a link from [1458745468](https://wiki.typo3.org/Exception/CMS/1458745468) as well.

Not an issue of this project but for TYPO3 Core project it would be great if introduction of new exceptions would require mandatory addition of documentation. This isn't the first exception code that showed absolutely no information at all on the wiki although the author who introduced the exception apparently had a very good idea about what he was doing and what consequences it had. Just referring to the changeset/issue would help to ease debugging and explain enough in most cases.

**Comment by NamelessCoder** [comment] 2016-06-15 11:00
Great, @dneuge!

> it would be great if introduction of new exceptions would require mandatory addition of documentation.

I think it already is, but I couldn't point you to where (except for the `Changelog` directory's raw RST files which are added in the TYPO3 master with each commit).

It is also completely possible that some rough edges were simply missed. I myself missed some while doing the Fluid reintegration.

In any case it's awesome that you documented these and big bonus points for adding workarounds!
