### ISSUE TITLE
[FEATURE] Read the Content template folder recursive

### ISSUE THREAD

**Issue by X-Tender** [FluidTYPO3/flux#1672] opened 2019-03-03 20:17 UTC
Currently the templateRootPath is only read on one level, but it also works when you change  this part
**Core.php : Line 116**
```php
foreach (GeneralUtility::getFilesInDir($templateRootPath, 'html') as $file) {
    static::registerTemplateAsContentType($extensionKey, $templateRootPath . $file);
}
```
into
```php
foreach (GeneralUtility::getAllFilesAndFoldersInPath([], $templateRootPath, 'html') as $file) {
    static::registerTemplateAsContentType($extensionKey, $file);
}
```
My question is, is there a reason why it is not implemented the recursive way? Its really handy to place the Content Templates in subfolders to make it a bit more organized / structured :)
Otherwise I would try to create a pull request.

**Comment by X-Tender** [comment] 2019-03-03 20:33
Ok just noticed that the "New Content" Overlay works but the actual render fails. 
However, would it be possible to implement this kind of recursive feature?

**Comment by NamelessCoder** [comment] 2019-04-24 09:48
Duplicate of https://github.com/FluidTYPO3/flux/issues/1569, please subscribe to that issue to follow status.

**Closed by NamelessCoder** 2019-04-24 09:48 UTC
