### ISSUE TITLE
flux:grid.column ignores Style argument

### ISSUE THREAD

**Issue by MediKathi** [FluidTYPO3/flux#1629] opened 2018-10-05 10:44 UTC
Hello there,

it seams, that flux (9.1.0) Ignors the style Attribute of flux:grid.column.
<flux:grid.column name="Col1" colPos="1" style="width:67%;"/>
the with has at least no effect. In this case I can Build a workaround with colSpan

**Comment by glucka** [comment] 2018-10-09 20:44
Duplicate of #1614

**Comment by NamelessCoder** [comment] 2018-10-10 07:47
I doubt this feature will be restored since the overrides that allowed it, have been removed. Regarding spans (both row and colspan) that is the way you are supposed to define relative widths also in the backend layout logic that Flux uses - so there's support for that use case, just not for arbitrary styles.

**Closed by NamelessCoder** 2018-10-10 07:47 UTC
