### ISSUE TITLE
The unique id of section/objects is not available when creating elements in a workspace.

### ISSUE THREAD

**Issue by MatthewC76** [FluidTYPO3/flux#1483] opened 2017-11-27 19:14 UTC
I am using the code below to create a series of accordions. On the LIVE site this works perfectly. However, when working in a workspace, the {section.object.id} is not present in the object. This makes creating accordions and adding content impossible in a workspace as the relationship between the content elements and the accordion panel doesn’t work.

Is this the correct way to do this, or is there another way to make this workspace compatible??

        <flux:form.section name="sections">
            <flux:form.object name="object">
                <flux:field.input name="title" />
            </flux:form.object>
        </flux:form.section>

        <flux:grid>
            <f:for each="{sections}" as="section">
                <flux:grid.row>
                    <flux:grid.column name="content.{section.object.id"/>
                </flux:grid.row>
            </f:for>
        </flux:grid>

Typo3 - 7.6.23
flux - 8.2.1
fluidcontent - 5.2.0
fluidpages - 4.1.0

**Comment by NamelessCoder** [comment] 2018-07-08 18:58
Hi @MatthewC76 - I will take the liberty of closing this issue. There is another issue which describes the cause for this problem and solving that one should automatically solve the same problem for the workspace versioning.

If you have any more information to add please drop a comment in that other issue ;)

https://github.com/FluidTYPO3/flux/issues/1372

**Closed by NamelessCoder** 2018-07-08 18:58 UTC
