### ISSUE TITLE
[BUG] - Flux fields BE localizations

### ISSUE THREAD

**Issue by ogrosko** [FluidTYPO3/flux#1559] opened 2018-06-14 13:34 UTC
Hi 
When field label is empty localization is not fetched correctly.
Eg. `<flux:field.text name="settings.text" />`
with correct localization in locallang.xml
```
<trans-unit id="flux.regularTextElement.fields.settings.text">
	<source>Text</source>
</trans-unit>
```
As label is used `settings.text`

Latest flux:dev-development state and Typo3 V 8.7.16

**Comment by dahaupt** [comment] 2018-07-11 23:07
@ogrosko Can you revalidate this with the latest released version 9.0.0, because I can't reproduce it.

**Comment by ogrosko** [comment] 2018-07-13 07:45
works fine with version 9.0 ;)

**Comment by NamelessCoder** [comment] 2018-07-13 09:45
That's good news - closing the issue then :)

**Closed by NamelessCoder** 2018-07-13 09:45 UTC
