### ISSUE TITLE
Flux settings inheritance resulting in broken flexform

### ISSUE THREAD

**Issue by wikipeter** [FluidTYPO3/flux#878] opened 2015-08-05 09:04 UTC
Hi there,

I upgraded my FT3 tools to the latest version (development) while running a 6.2 project. I have different page templates, every page has multiple flux settings. 2 of those settings appear in every single page template.

Settings which appear in all page templates:

```html
<flux:field.checkbox name="settings.showSiteTitle" label="Display Site Title"/>
<flux:field.checkbox name="settings.showBreadcrumb" label="Display Breadcrumb"/>
```

If the root page has a template assigned, and those two properties are set to true for current and subpages, i face those two options also set for a child page with a different page template assigned (inheritance as I would expect it).

But if the child page is saved with flux settings like those:

```html
<flux:field.checkbox name="settings.showSiteTitle" label="Display Site Title"/>
<flux:field.checkbox name="settings.showBreadcrumb" label="Display Breadcrumb"/>
<flux:field.checkbox name="settings.showContactBox" label="Display Contact Box"/>
<flux:field.checkbox name="settings.enableNewsletterApplication" label="Enable Newsletter subscription in Meta Navigation" />
<flux:field.input name="settings.project.address.street" label="Street and Street Number"/>
<flux:field.input name="settings.project.address.city" label="Zipcode an City"/>
```
results in a flexform like this:

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<T3FlexForms>
    <data>
        <sheet index="options">
            <language index="lDEF">
                
                <field index="settings.showBreadcrumb">
                    <value index="vDEF">1</value>
                </field>
                <field index="settings.showContactBox">
                    <value index="vDEF">1</value>
                </field>
                
                <field index="settings.project.address.street">
                    <value index="vDEF"/>
                </field>
                
            </language>
        </sheet>
    </data>
</T3FlexForms>
```

The following settings are missing and replaced by an empty line instead:

* settings.showSiteTitle (inherited)
* settings.enableNewsletterApplication
* settings.project.address.city

In such a case hiding a page via context menu in page tree results in a DirectExt exception or some backend error appearing at the top.

Any clues if this is my fault rather than a bug?

Cheers
Peter

**Comment by NamelessCoder** [comment] 2015-09-10 21:13
Hey Peter - could you try this again but before you do, make sure you clean all pages in the root line, specifically the `tx_fed_page_flexform` and `_sub` fields? This could be because one of those fields has a previously saved value that was never cleared because Flux "forgot" about it after a template was changed. That's by design and also slightly because it's unavoidable. If we didn't keep these and you changed the template and then changed back again, all values would be lost.

The alternative way to cause this clearing is to use the install tool's "clean flexform data" feature, but that will load the DS from Flux and if there are any bugs in Flux, doing that would just leave those values in there. The only really thorough test would be to start with completely blank fields.

Let us know how it turns out please! Also if you found the cause in something else - we still like to hear about it.

**Comment by NamelessCoder** [comment] 2015-09-28 17:30
@wikipeter Any update about this one? I've tried to reproduce your problem but can't, so I'm fairly sure it's caused by old DB values. If I don't hear from you (I'll give it a couple more days) I'll take the liberty of closing this one as unable to reproduce.

**Comment by mneuhaus** [comment] 2015-11-07 14:49
closing for now since there's no further information to go by.
furthermore starting today the development branch won't be updated for 6.2 anymore,
we created a new branch legacy for 6.2 that will receive important bugfixes and such, 
but new features from now on will not be supported on 6.2 anymore.

**Closed by mneuhaus** 2015-11-07 14:49 UTC
