### ISSUE TITLE
Translated content element not translating all fields

### ISSUE THREAD

**Issue by MrMooky** [FluidTYPO3/flux#1178] opened 2016-09-05 14:41 UTC
Hello,

we're currently struggling with a weird bug we can't find a fix for, thus asking here seems to be the only option.

We have a Content Element with multiple fields. One of them is not being translated correctly. The German field looks like this:

![screen shot 2016-09-05 at 4 35 55 pm](https://cloud.githubusercontent.com/assets/3603346/18251012/ed7b2a6c-7386-11e6-89d6-246d17e67c35.png)

For the translation, we entered different text:

![screen shot 2016-09-05 at 4 36 51 pm](https://cloud.githubusercontent.com/assets/3603346/18251025/009a7ddc-7387-11e6-8146-48593db19941.png)

But this text is neither showing up within the backend, nor the website.

![screen shot 2016-09-05 at 4 38 03 pm](https://cloud.githubusercontent.com/assets/3603346/18251053/24479486-7387-11e6-9954-62470ce932e4.png)

As you can see above, the other fields are fine. There is nothing special about this field, a simple input:

`<flux:field.input name="title4" label="Unterüberschrift" />`

We tried deleting, and creating a new translation, deleting the original reference and creating a completely new one, but the translation of this field is not showing up.

**Comment by webdev2027** [comment] 2016-09-06 06:28
Hi, must be a caching problem. Clear Cache at the install tool, or use EXT:flush_language_cache

Use
`<flux:field.input name="title4" default="LLL:EXT:yourprovider/Resources/Private/Language/locallang.xlf:fce.title4" />`

and two locallang files (de.locallang.xlf and locallang.xlf)

**Comment by MrMooky** [comment] 2016-09-06 07:15
I think you misunderstood. It's not about the Label, it's about the input within the field "title4". In German it says "Wir sind für Sie da!", when translating it and changing the value to "We are there for you!", it's not being translated but the German text is used instead.

**Comment by webdev2027** [comment] 2016-09-07 06:22
Ok, but with your other field "Noch Fragen/Get questions" is everything fine?! Have you already change the name from "title4" to "loremxyz" f.e. Maybe "title4" is already in use? But you did it right?  Be sure of your translation code is correct. 

```
<trans-unit id="flux.fce.fields.title4" xml:space="preserve">
	<source>We are there for you!</source>
</trans-unit>
```
... target de.locallang.xlf
```
<trans-unit id="flux.fce.fields.title4" xml:space="preserve">
	<target>Wir sind für Sie da!</target>
</trans-unit>
```
That's weird ..

**Comment by MrMooky** [comment] 2016-09-07 09:53
Yes, the other fields are fine and work as expected. We're not using language files for the backend, as it is not needed. The field exists only once. We checked everything we could think of, the last solution was to ask here.

**Comment by NamelessCoder** [comment] 2017-03-26 14:55
@MrMooky would you mind trying this again with `dev-development` branch of Flux? Not too long ago there was a fix to correctly set the language UID when rendering our previews. This could be why your labels aren't being translated consistently.

Oh and don't forget that the TYPO3 core has removed support for translating FlexForm fields individually - the entire `flex` field is now translated, which means every single XML-stored value exists in both the original and translated records. As far as I can tell from your description you've already eliminated old XML values as a possible cause, so the problem is either the incorrect language UID - or a separate problem in Flux when resolving the XML values used when rendering the preview.

**Comment by MrMooky** [comment] 2017-03-28 07:45
We were not able to reproduce the problem with newer versions of TYPO3 and Flux. We're not sure what fixed it in the end, but it's working now.

My colleague mentioned that [Compatibility6](https://typo3.org/extensions/repository/view/compatibility6) might've caused the issue, but again, we're not sure.

**Comment by NamelessCoder** [comment] 2017-03-28 10:12
Thanks for the note about `compatibility6` - that could indeed be an explanation (I don't know for sure). Flux is no longer remotely compatible with TYPO3v6 so anything that changes behavior to v6 could very well be incompatible with the way Flux works. For one, data structures may be processed differently.

Will close this as resolved. If anyone else comes across this, try deactivating `compatibility6` and if that solves it, it's time to migrate your code and remove `compatibility6` ;)

**Closed by NamelessCoder** 2017-03-28 10:12 UTC
