### ISSUE TITLE
Flux Grid is crashing in Backend Preview (IMPORTANT)

### ISSUE THREAD

**Issue by Marc-Bauer** [FluidTYPO3/flux#1086] opened 2016-02-26 10:12 UTC
At version 7.6.4 of TYPO3 Flux Grid Preview is crashing. 

Error Message is:
#1: PHP Warning: Invalid argument supplied for foreach() in /var/www/lib/TYPO3_core/typo3_src-7.6.4/typo3/sysext/backend/Classes/View/PageLayoutView.php line 1812

The error will be created if you switch from the column into the language view in pages module.

**Comment by NamelessCoder** [comment] 2016-02-28 20:00
What is the content of your Preview section and where is the preview section being rendered (Page, Content) - and what are the language and page translation settings? I'm unable to reproduce this problem by creating a new site, adding a language and selecting a `fluidpages` template with a Preview section and inserting a content element with a Preview section; one content element using a nested content grid and another using a simple text as preview. All of which is working.

Tried with both TER and development versions of Flux with same result.

**Comment by Marc-Bauer** [comment] 2016-02-28 21:46
If you have a page with some content elements (fluidcontent or core elements) and in other languages in this page these content elements are not all translated. The error message is coming. If you have all content elements translated there is no bug... maybe it could be a core or a flux problem I don't. If you want I can send you an image of the problem :)

**Comment by NamelessCoder** [comment] 2016-02-29 16:15
https://review.typo3.org/#/c/46925/ should fix it but I await feedback on what would be the proper way to make sure this cache is filled before creating the new language button.

**Comment by Sonja-Schubert** [comment] 2016-03-02 08:00
Hey guys, something new here? It would be great to have a solution soon as the security update needs to be done. Wouldn't it be possible to redefine the newLanguageButton function in the extension? What do you think? Only as long as the core patch issn't committed or a better solution is there. Thank you for your help!

**Comment by torvitas** [comment] 2016-03-02 11:03
We had to revert/delay the 7.6.4 update too. We are really looking forward to having this one fixed.

**Comment by fnagel** [comment] 2016-03-15 16:55
Run into this issue today. Core patch works for me.

**Comment by NamelessCoder** [comment] 2016-03-23 22:04
TYPO3 release 7.6.5 will solve this issue (by checking if the cache is filled); the core patch linked to above fixes it. There is no publicly available method for filling said cache before calling the method so unfortunately we can't create a workaround - but luckily 7.6.5 is right around the corner now.

**Closed by NamelessCoder** 2016-03-23 22:04 UTC

**Comment by manuelbachl** [comment] 2016-04-18 17:59
Is this really resolved? For me (just updated to 7.6.5 right now) the error still gets thrown...

**Comment by NamelessCoder** [comment] 2016-04-19 08:57
@manuelbachl The issue in this thread is solved, maybe you have another issue. Your template code does not appear to be related to the issue in this thread since that issue concerns grids in the Preview section - and your form does not have any content areas. Are you sure it is the same error?

**Comment by manuelbachl** [comment] 2016-04-19 09:26
Oh, you're right - have clicked arount those issue-mentions and have been landing here. My topic is related to the flux:form.container instead... Thought this has been resolved, too. I'm goung to move my comment to the relating issue.

**Comment by fnagel** [comment] 2016-04-29 15:30
Just updated to 7.6.6 (from 7.6.4) and everything works fine -- without the patch.
