### ISSUE TITLE
[ Typo3 7.6.2 + Flux 7.3.0-dev + GridElements 7.0.5 ] Cannot position a Grid Element inside a Flux Column

### ISSUE THREAD

**Issue by julianxhokaxhiu** [FluidTYPO3/flux#1073] opened 2016-02-12 10:55 UTC
Everytime I try to do this, the element just "disappear". No trace of it, even on "List".

Any clue?

Thanks

**Comment by almirbi** [comment] 2016-02-12 12:40
Does it maybe happen in draft mode only? Also, could you please elaborate a bit more on what exactly you mean by Grid Element, and Flux column?

We have a problem that when in draft move, if we move an existing content element ( any, let's say Picture element ) into a Flux Content element ( a content element added with the Flux extension ) which has it's own "content area" - the moved item disappears.

**Comment by julianxhokaxhiu** [comment] 2016-02-12 12:55
Well, I guess it's nothing more to be said.

Anyway, I'm using the latest `dev` version ( updated today ) of every extension related to `flux` ( `fluidbackend`, `fluidcontent` etc. ).

The workspace is the default one ( we don't use them, so I guess is the `live` ) one.

About positioning, I refer to Grid Elements created from the backend, and "moving the element by dragging it with the mouse" over the a flux column, created inside a custom flux CE ( with 1 row and 4 cols ). Everytime you try to do that the element just disappear.

**Comment by mjankiewicz** [comment] 2016-02-12 14:26
Hi, I had similar issue: https://github.com/mjankiewicz/flux/commit/7f6696cfe3f04692a9c242ac36915517058dd936

**Comment by julianxhokaxhiu** [comment] 2016-02-15 11:15
@NamelessCoder any clue?

**Comment by NamelessCoder** [comment] 2016-04-11 00:01
Possibly / very likely duplicate of any number of currently open issues describing this same symptom in various ways. Will try to merge those issues somehow.

**Closed by NamelessCoder** 2016-04-11 00:01 UTC
