### ISSUE TITLE
Wrong settings for flux:field.tree

### ISSUE THREAD

**Issue by doerler** [FluidTYPO3/flux#1656] opened 2018-12-17 09:16 UTC
When using a tree (flux:field.tree) and opening the content element a separate ajax request is made to get the tree information. In this request the page ID isn't properly obtained, which results in wrong extension settings. None of the currently implemented methods in `\FluidTYPO3\Flux\Configuration\BackendConfigurationManager::getPrioritizedPageUids` covers this scenario.

$_GET data for this request:

```php
[
    'ajaxID' => '/ajax/record/tree/fetchData',
    'ajaxToken' => '1234567890123456789012345678901234567890',
    'tableName' => 'tt_content',
    'fieldName' => 'pi_flexform',
    'uid' => '12053',
    'recordTypeValue' => 'fluidcontent_content',
    'dataStructureIdentifier' => [
        'type' => 'flux',
        'tableName' => 'tt_content',
        'fieldName' => 'pi_flexform',
        'record' => [
            'uid' => '12053'
        ],
    ],
    'flexFormSheetName' => 'options',
    'flexFormFieldName' => 'myTree',
    'flexFormContainerName' => '',
    'flexFormContainerIdentifier' => '',
    'flexFormContainerFieldName' => '',
    'flexFormSectionContainerIsNew' => '',
    'command' => 'edit',
]
```
The correct page ID could be obtained with $_GET['tableName'] and $_GET['uid'].

**Used versions**
Typo3 8.7.20
flux 8.2.1
fluidpages 4.1.0
fluidcontent 5.2.0

In flux 9 the core's BackendConfigurationManager is used which also doesn't consider this case.

**Comment by NamelessCoder** [comment] 2018-12-17 15:47
This cannot be fixed in Flux - as you state, we use the core's ConfigurationManager and it does not consider every possible way of passing pid. If you wish for this to be changed please open a bug report / feature request on the TYPO3 core bug tracker. The custom BackendConfigurationManager no longer exists in Flux v9 and the v8 branch is no longer maintained.

Part of the problem is that TYPO3 is not consistent in passing the page UID in backend context especially. In a perfect world, any link you generated would always contain `?id=123` like the frontend requests would, unless the link truly has no page context or the context is page UID zero. That said, adding it to the core's BackendConfigurationManager could be a good idea as it also helps to collect the various contexts that pass UID in different ways.

You can file a new issue for the TYPO3 core at https://forge.typo3.org/projects/typo3cms-core/issues/new but please check open issues first to see if it's already recorded.

**Closed by NamelessCoder** 2018-12-17 15:47 UTC
