### ISSUE TITLE
flux:form.container not working with TYPO3 7.3

### ISSUE THREAD

**Issue by flatchar** [FluidTYPO3/flux#863] opened 2015-07-28 10:58 UTC
Hi,
when I create a 
flux:form.container it always returns:

``Section expected at *containerName* but not found``

TYPO3: 7.3.1
flux: 7.2.1
fluidcontent: 4.2.4

best,
flatchar

**Comment by jmverges** [comment] 2015-07-28 14:31
Hi @flatchar, could you paste the complete file?

**Comment by flatchar** [comment] 2015-07-28 14:39
Hi @jmverges,
sure. :)

https://gist.github.com/flatchar/071225234cc1bf1f8394

Everything works fine except ContainerViewHelper.

best,
flatchar

**Comment by NamelessCoder** [comment] 2015-07-28 19:03
The usage is valid. The error is thrown by TYPO3 and is caused by the recent remodelling of FormEngine. The exact reason is that whomever created the core patch did not foresee and add support for an existing feature: containers as a "dynamically added set of fields" also *outside* sections.

The problem must be reported to and fixed in the TYPO3 core as it affects not only Flux but affects any source of TCEforms definitions that use this way of nesting.

**Closed by NamelessCoder** 2015-07-28 19:03 UTC
