### ISSUE TITLE
<flux:field.multiRelation> autocomplete breaks when fluidcontent element not saved yet

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/flux#1272] opened 2017-01-06 10:00 UTC
I've got a fluidcontent element with a `<flux:field.multiRelation>` field.

Entering letters in its autocomplete field sends an AJAX request to the server, and this one throws an HTTP 500 error because of an exception:

> #1: PHP Warning: explode() expects parameter 2 to be string, array given in /var/www/site/htdocs/typo3conf/ext/fluidcontent/Classes/Provider/ContentProvider.php line 203

The exception only occurs when the content element has not been saved yet. Once it has been saved, autocompletion works fine.

This happens with fluidcontent 4.4.1 and flux 7.4.0.

Code:
```
<flux:field.multiRelation name="settings.entries" table="tx_example" minItems="1" maxItems="1000">
    <flux:wizard.suggest/>
</flux:field.multiRelation>
```

----
Exception trace:
```
19 TYPO3\CMS\Core\Error\ErrorHandler::handleError(2, "explode() expects parameter 2 to be string, array given", "/var/www/site/htdocs/typo3conf/ext/fluidcontent/Classes/Provider/ContentProvider.php", 203, array)
18 explode(":", array)
17 FluidTYPO3\Fluidcontent\Provider\ContentProvider::getControllerExtensionKeyFromRecord(array)
16 FluidTYPO3\Flux\Provider\AbstractProvider::getControllerPackageNameFromRecord(array)
15 FluidTYPO3\Flux\Provider\AbstractProvider::resolveFormClassName(array)
14 FluidTYPO3\Flux\Provider\AbstractProvider::getForm(array)
13 FluidTYPO3\Fluidcontent\Provider\ContentProvider::getForm(array)
12 FluidTYPO3\Flux\Provider\AbstractProvider::postProcessDataStructure(array, array, array)
11 FluidTYPO3\Flux\Backend\DynamicFlexForm::getFlexFormDS_postProcessDS(array, array, array, "tt_content", "pi_flexform")
10 TYPO3\CMS\Backend\Utility\BackendUtility::getFlexFormDS(array, array, "tt_content", "pi_flexform")
9 TYPO3\CMS\Backend\Form\Wizard\SuggestWizard::overrideFieldNameAndConfigurationForFlexform("tt_content", "pi_flexform|data|options|lDEF|settings.entries|vDEF", array, NULL)
8 TYPO3\CMS\Backend\Form\Wizard\SuggestWizard::searchAction(TYPO3\CMS\Core\Http\ServerRequest, TYPO3\CMS\Core\Http\Response)
```

**Comment by NamelessCoder** [comment] 2017-01-06 11:53
This is, unfortunately, a TYPO3 core bug. The only course of action we in FluidTYPO3 can take, is to hide the FlexForm field from view until the record is saved at least once. The source of the problem is the rewritten FormEngine which no longer provides a full or partial record (full if saved, partial with default values if not saved) to the hooks which resolve the DS. Because this vital variable is no longer transmitted to hooks, Flux becomes incapable of resolving the correct DS based on CType or other parameters of the not-yet-saved record.

It's not a pretty situation but there's really not much we can do about it - other than preventing such things by not presenting the field until the DS can consistently be resolved.

**Comment by cweiske** [comment] 2017-01-24 09:54
I've opened a bug report for TYPO3 core: [Bug #79434: Hooks do not get full or partial record from FormEngine](https://forge.typo3.org/issues/79434)

**Comment by NamelessCoder** [comment] 2017-02-12 11:32
The overall bug here is now solved - and we can produce DS also for new records! - but it may come with some assembly required, depending on your setup.

If your Provider or template from which the Flux form is extracted (via the Provider) depends on fields from the record which are NOT present in `$GLOBALS['TCA']['tt_content']['ctrl']['useColumnsForDefaultValues']` you will need to add the field names that you require, to this list, using TCA overrides.

**Closed by NamelessCoder** 2017-02-12 11:32 UTC

**Comment by cweiske** [comment] 2017-02-12 14:05
Could you please point me to a commit where this is solved? The TYPO3 bug I opened is still open.

**Comment by NamelessCoder** [comment] 2017-02-13 01:01
https://github.com/FluidTYPO3/flux/commit/c0e01b644bed129e908a567e1c8cd991c77124ac solved it from the Flux side - seems we now receive enough data to compile a DS, and we started passing this (limited) data in XHR requests.

Not sure if you can close the core issue... but it looks like it.
