### ISSUE TITLE
Flux <flux:form> Icon-Path not working

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/flux#1423] opened 2017-06-22 11:37 UTC
I am not able to define a working Icon for a Flux-Template:
`
<flux:form id="page-default" label="My Layout" options="{icon: '...}">
...
</flux:form>
`
I recently tried this using f:uri.resource ViewHelper:
{f:uri.resource(extensionName: 'my_extkey', path: 'Icons/bootstrap/glyphicons_113_justify.png')}

This worked once by prefixing the output with some relative Path (../../../). This was never an ideal solution and since using TYPO3 v.8 and flux 8.2.1, fluidpages 4.1.0 and fluidcontent 5.2.0 it still is not working at all.

Depends to:
TYPO3 v.8 and flux 8.2.1, fluidpages 4.1.0 and fluidcontent 5.2.0

Related to: #891

**Comment by coding46** [comment] 2017-07-18 16:59
`<flux:form.option.icon>EXT:provider/Resources/Public/Icons/Default.svg</flux:form.option.icon>` should do the magic.

**Comment by fnagel** [comment] 2017-07-20 08:25
`<flux:form.option.icon value="EXT:myext/Resources/Public/Icons/grid.svg" />` does not work (taken from #1369). Now testing @coding46 suggestion.

This seems like a similar issue we had with symlinks before: : https://github.com/FluidTYPO3/fluidcontent/pull/343

**Comment by fnagel** [comment] 2017-07-25 08:44
@cbrunet Your suggestion does not work. I guess this issue is some kind of a regression (https://github.com/FluidTYPO3/fluidcontent/pull/343)

**Comment by coding46** [comment] 2017-07-25 09:06
@fnagel Just for clarity:
I'm using TYPO3 8.7.3, Flux 8.2.1, Fluidcontent 4.1.0 and Fluidpages 5.2.0 and the Fluid snippet mentioned above. All icons appear in NewContentWizard and Page Layouts Tab correctly.

**Comment by fnagel** [comment] 2017-07-25 09:14
@coding46 Same setup here (using composer for setup) but it doesn't work.

**Comment by cweiske** [comment] 2017-09-01 11:01
It works here with TYPO3 8.7.4, flux 8.2.1, fluidcontent 5.2.0, fluidpages 4.1.0.

**Comment by fnagel** [comment] 2017-09-01 11:33
It works in my VM but it doesn't work on the production server. We had a similar issue with icon path resolving with fluidcontent, fixes here: https://github.com/FluidTYPO3/fluidcontent/pull/343

Some more discussion is here: https://github.com/FluidTYPO3/flux/issues/943

**Comment by NamelessCoder** [comment] 2017-10-29 16:29
As @fnagel writes, icon references should be written as non-relative references, for example in the `EXT:...` format. The other options you have include convention-based file lookups - if your template filename is `Default.html` and it's in the `Content` templates folder, your expected icon filename will be `EXT:yourext/Resources/Public/Icons/Content/Default.(png|gif|jpg|svg)`.

Closing this issue - @fnagel if you still face the problem in different behaviors on various systems it would be great if you could open a new issue about that specifically. I'm not sure what we could do about it since I suspect this is something inside TYPO3 or the IconFactory - but I don't mind taking a deeper look at it.

**Closed by NamelessCoder** 2017-10-29 16:29 UTC

**Comment by VivekNitsan** [comment] 2023-05-10 06:31
`<flux:form.option.icon value="EXT:extention/Resources/Public/Icons/Example.svg" />`

is not working in typo3 v11

**Comment by nitsan-technologies** [comment] 2023-06-05 15:20
This code will work 

`<flux:form.option.icon value="example-icon"/>` in your fluid

```
return [
    'example-icon' => [
        'provider' => \TYPO3\CMS\Core\Imaging\IconProvider\SvgIconProvider::class,
        'source' => 'EXT:pg_bea_theme/Resources/Public/Icons/Example.svg',
    ],
];
```  
and this code for icon register

**Comment by DanYouCan** [comment] 2023-06-06 06:16
@nitsan-technologies 
Thanks a lot for your support. I already tested it. The icon register works like a charm!

**Comment by MrMooky** [comment] 2024-09-24 13:43
> This code will work
> 
> `<flux:form.option.icon value="example-icon"/>` in your fluid
> 
> ```
> return [
>     'example-icon' => [
>         'provider' => \TYPO3\CMS\Core\Imaging\IconProvider\SvgIconProvider::class,
>         'source' => 'EXT:pg_bea_theme/Resources/Public/Icons/Example.svg',
>     ],
> ];
> ```
> 
> and this code for icon register

That was the ONLY thing that worked for me in a 11.5 installation. ✨
