### ISSUE TITLE
Fluidcontent container: Single child element does not get translated in page view

### ISSUE THREAD

**Issue by SomeBdyElse** [FluidTYPO3/flux#1071] opened 2016-02-09 12:04 UTC
Trying to translate a single child element from a fluidcontent container element, the translation wizard does not create the translated element. 

## Environment
Extension    | Branch     |  hash
------------ | ---------- | -------
TYPO3.CMS    |7_6         | f21b04d
fluidcontent |development | af6014b
flux         |development | 52bb0f5 
vhs          |development | a349d71

## Steps to reproduce the issue
1. Install the attached extension for a simple 2col fluidcontent container. [fluidcontent_example.tar.gz]  (https://github.com/FluidTYPO3/flux/files/123014/fluidcontent_example.tar.gz)
1. In the TYPO3 Backend, create a second (sys_)language. In my case, it is English (English, en, gb). 
1. Create a page in the page tree
1. Create an English translation for that page
1. In the Page view module, switch to "Languages" in the function menu
1. Create a container element in the default language, using the "Container" element from the fluidcontent_example extension
1. Create one child element in each column of the container element. All in default language
1. Hit the "Translate" button in the English column
1. In the translation wizard, click translate and next. Once it's done click finish
1. Delete the _translation_ of the left element. Now the page module should look like the attached image

![image c](https://cloud.githubusercontent.com/assets/243504/12915728/6410cb86-cf2d-11e5-9c7f-a8486ddda8a1.png)

1. Hit the translate button in the left column of the foreign language container, trying to get your translation back
1. Click through the wizard, as done before (use translate, not copy). Note that only the Container element appears in the record summary. 
1. At the end of the wizard, note that there is no new element

## Expected outcome
I would expect that the translation wizard creates a new translation of the left child element and places it in the left column of the foreign container.

**Comment by NamelessCoder** [comment] 2016-04-11 00:05
Known core issue, still has no official fix. Duplicate of https://github.com/FluidTYPO3/flux/issues/1099 which we will keep open until there is a fix in the TYPO3 core - please follow it there!

**Closed by NamelessCoder** 2016-04-11 00:05 UTC
